### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by YerkoPalma** [pagekit/vue-resource#244]
Hi, thanks for this repo, is really useful and well done. However, I think that the docs can be improved a lot. It happens to me that when I have a specific issue with vue-resource I have to dig into the issues and pull requests to find an answer, so I suggest to improve documentation, by creating a `gh-pages` branch, and using [gitbook](https://www.gitbook.com/) like [vue-router](http://vuejs.github.io/vue-router/en/index.html) and [vuex](http://vuejs.github.io/vuex/en/index.html) does.

What I would add to existing documentation
- A litle bit about CORS usage
- Examples and reference of file transfer
- Better examples of interceptors usage
- A whole topic about testing
- And maybe a FAQ section with the most repeated issues?

thanks for readings :smile:

**Comment by steffans** [comment]
@YerkoPalma Thanks for your suggestions. Currently all documentation files are in `/docs` in folder. If you like help me out on a topic you suggested, please send me a pull request. Gitbook looks nice, i will try to move the current docs to `gh-pages`.

**Comment by caiquecastro** [comment]
I don't know if you have already submitted a PR. But the `finally` clause is a good thing to document. Although it's part of native JS, the changes on the API compared to the native `fetch` may make someone else confused.
