### ISSUE TITLE
stop response in interceptors

### ISSUE THREAD

**Issue by Centaur** [pagekit/vue-resource#253]
We use global response interceptor to do authentication: 
when the server returns 401, call vue-router to go to the Login route. After this point, the response should not be processed by any other interceptors or by user code any more. 
The problem is that, if I understand correctly according to [the code](https://github.com/vuejs/vue-resource/blob/master/src/http/interceptor.js#L29), the response will be sent down though the interceptor chain and to user code after all.
Can we have something like `response.stop` method to prevent it from further processing?

**Comment by YerkoPalma** [comment]
I don't think this would be a good idea. In the particular case of authentication, you should handle logged out users in the backend, so when you have that error 401, send or update some cookie/header to inform that you are logged out, and the request that triggered the interceptor should handle that response. I do it like this, and I can't imagine other use case when stopping the response would be necesary, in fact it would be a problem. How would you handle that missing response? it isn't an error response, it's just a missing response

**Comment by listen-lavender** [comment]
how to user router.go of vue-router in vue.http.interceptors of vue-resource, i want to redirect according to the response status

**Comment by listen-lavender** [comment]
how to use router.go of vue-router in vue.http.interceptors of vue-resource, i want to redirect according to the response status

**Comment by Centaur** [comment]
@listen-lavender In your top level component ( the first argument of `router.start` call), define:

```js
created() {
  let self = this
  Vue.http.interceptors.push({
      response: function(response) {
         if(response.status === 401) {
           self.$route.router.go(...) 
         }
      }
  }
}
```

**Comment by listen-lavender** [comment]
yes, just like your example, but it doesn't work, maybe i am in wrong way. @Centaur

**Comment by listen-lavender** [comment]
it is the same to global setting,  it can't stop response in interceptors. Maybe the issue https://github.com/vuejs/vue-resource/issues/5 is a solution.

**Comment by listen-lavender** [comment]
it is the same to global setting, it can't stop response in interceptors. Maybe the issue #5 is a solution. @Centaur

**Comment by Centaur** [comment]
@listen-lavender Of course it can not. If it could, this issue would not exist in the first place.

**Comment by steffans** [comment]
Have look here i just updated the interceptors in the develop branch, https://github.com/vuejs/vue-resource/issues/224#issuecomment-226107447

**Comment by alexjoverm** [comment]
@steffans I was struggling for a while because the documentation of the interceptors refers to the v0.8.0 but when you install it through `npm install vue-resource` the v0.7.4 was installed by default.

Not sure if that's something to check out.

**Comment by JounQin** [comment]
@steffans Hello, I'm sorry but I still don't know how to stop response in interceptors.

When response is an error from server, how to handle the error globally and stop the Promise.resolve or Promise.reject?

I don't want to handle the error like 40* specifically in every component.

**Comment by MonkeyKiky** [comment]
At first, my English is poor.
I just encountered this problem, my solution is as follows.
```javascript
Vue.http.interceptors.push((req, next) => {
  next((res) => {
    if (!res.ok) {
      // toast message like error or warning, or do other things you like
    }
    // !this is the focus
    // in source code, if return has no attribute of 'ok', it reject, add ‘ok’:true, it always resolve**
    // now $http...then((res) => {}), this res is the response from backend
    return {...res.body, ok: true}
   })
})
```
