### ISSUE TITLE
Refused to set unsafe header "Origin"

### ISSUE THREAD

**Issue by christophwolff** [pagekit/vue-resource#257]
Hi,
iam trieing to modify my header but if i do so i get: `vue-resource.min.js:7 Refused to set unsafe header "Origin"`

I have a cross domain origin api access. So i need to modify the header.

Any idea how to do this?

The code:

```
...
getStationInfos: function(stationInfoURL) {
            try {
                var options = {
                    xhr: {
                        withCredentials: true
                    },
                    beforeSend: function(request) {
                        console.log(request);
                        request.headers.Origin = "http://www.domain.de";
                    }
                };
                this.$http.get(stationInfoURL, {}, options).then(function(infos) {
                    this.$set('currentAudioStream.infos', infos.data);
                });
            } catch (e) {
                console.log(e);
            }
        },
...
```

I tried to set the Origin header in the Vue Instnace. Same error...

Thank you

**Comment by ChacesXia** [comment]
i have same problem about it

**Comment by christophwolff** [comment]
I solved it by setting the right header on the source. I.E your api server.
ChacesY <notifications@github.com> schrieb am So., 10. Apr. 2016 um 18:07:

**Comment by ChacesXia** [comment]
How set your server? My server is Nginx . I set my nginx server as same as [http://enable-cors.org/server_nginx.html].but post method doesn't work, This is error:
`Refused to set unsafe header "origin"
POST http://121.249.216.217/auth/login 500
XMLHttpRequest cannot load http://121.249.216.217/auth/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 500.`
Can you fix it? Thanks

**Comment by christophwolff** [comment]
Try this

http://serverfault.com/questions/162429/how-do-i-add-access-control-allow-origin-in-nginx

ChacesY <notifications@github.com> schrieb am Mo., 11. Apr. 2016 um 02:06:

**Comment by chenxuezhou** [comment]
chrome deny

**Comment by kulwindermatharu** [comment]
<h1>Chrome Problem</h1>
