### ISSUE TITLE
Cannot set default values in vue instance

### ISSUE THREAD

**Issue by jasontll** [pagekit/vue-resource#263]
I have an issue when trying to set the default header values in the vue instance using:

`new Vue({

```
http: {
  root: '/root',
  headers: {
    Authorization: 'Basic YXBpOnBhc3N3b3Jk'
  }
}
```

})`

in my console.log I get Vue.http.headers:
`Object {put: Object, post: Object, patch: Object, delete: Object, common: Object…}
common: ObjectAccept: "application/json, text/plain, */*"__proto__: Object
custom: ObjectX-Requested-With: "XMLHttpRequest"__proto__: Object
delete: ObjectContent-Type: "application/json"__proto__: Object
patch: ObjectContent-Type: "application/json"__proto__: Object
post: ObjectContent-Type: "application/json"__proto__: Object
put: ObjectContent-Type: "application/json"__proto__: Object__proto__: Object`

Note the Authorization headers is nowhere to be found in the common object.

However, it worked if I use the global configuration like:
`Vue.http.options.root = '/root';
Vue.http.headers.common['Authorization'] = 'Basic YXBpOnBhc3N3b3Jk';` 

I'd like to set the headers in Vue instance to keep the codes intact. Anyone has any suggestions?

**Comment by 1647917675** [comment]
https://github.com/vuejs/vue-resource/blob/master/docs/config.md

**Comment by do-web** [comment]
whats the solution? i have the same issue.
