### ISSUE TITLE
'Vue.http.interceptors' it does not work; but I can get the global headers setting

### ISSUE THREAD

**Issue by yhZhouYh** [pagekit/vue-resource#272]
Vue.http.headers.common['uid'] = router.app.$route.params.id || window.localStorage.getItem('uid') //可删除
Vue.http.interceptors.push(
  {
    request (req) {
      console.log('Intercepted REQ:', req)
      return req
    },
    response (res) {
      console.log('Intercepted RES:', res)
      return res
    }
  }
)

I want to set the global loading for getting data from the server. what's the way to set ? Is the interceptors a good way?

**Comment by yhZhouYh** [comment]
well,I have tried again,but I found that the global interceptors can not work in vue-router's data hook function..:(

**Comment by vianvio** [comment]
similar issue met, I set interceptors to get 401 and do a redirect to login page.
sometimes it works, but sometimes it doesn't

**Comment by jokeronaldo** [comment]
Interceptors just don't work.

**main.js**
```
import Vue from 'vue'
import VueRouter from 'vue-router'
import VueResource from 'vue-resource'
// import VueSocketio from 'vue-socket.io'
import routes from './http/routes'
import app from './components/App'

Vue.use(VueResource)
Vue.use(VueRouter)

// Vue.http.options.root = '/'

Vue.http.interceptors.push((request, next) => {
  console.log('ENTERING ROUTE')
  next()
})

// Vue.use(VueSocketio, 'http://192.168.0.102:1337')

const router = new VueRouter()

router.map(routes)

router.redirect({
  '*': '/basic/login'
})

router.start(app, '#app')
```

When changing/enter route nothing happens :sob: Help, please.

**Comment by williamokano** [comment]
@jokeronaldo are you trying to intercept when changing state?

Interceptors just intercept the this.$http.METHODS calls.

**Comment by jokeronaldo** [comment]
@williamokano I tought it works for vou-router route changing. It just works for Vue.http.METHOD? I mean, when you change a route, it's basically a request, IMO it's a real request.

What I'm trying to do is a middleware for every vue-router route, calling a method before entering a route. Is it possible?

**Comment by williamokano** [comment]
Well, I'm not a vue expert (to be honest, I just started a few days ago) but I think that just work for the plugin calls.

What you're trying to do probably can be done with an middleware.

Please check this out [http://vuex.vuejs.org/pt/middlewares.html](http://vuex.vuejs.org/pt/middlewares.html) PS.: **not tested**
