### ISSUE TITLE
Resource API need to set options per request

### ISSUE THREAD

**Issue by Nandiin** [pagekit/vue-resource#283]
When using Http API, I can set distinct options for every request by calling `get\post\put\etc(url, data, param, options)`
But when using Resource API, It requires to set a resource-scope global options when creating that resource `resource = Vue.resource('some{/where}', actions, params, options)`
This is pretty reasonable when a `Resource` stands for a specific resource because we are not likely to need serverl options upon it. However, thanks to `url-template`, a `Resource` can be very complicated when using params, consider this: `contents = Vue.resource('mydomain/contents{/id{/resType}})`
and corresponding backend api responds as:
- `/contents`: `'GET'` response a json object describing all contents saved in database
                   `'POST'` add a content and response it's id
- `/contents/id`: `'GET'`response a content, 'PUT' update a content 
- `/contents/id/resType`: `'GET'` response a content-specific resource, e.g. a content has a background image and we can fetch it like `/contents/1/background`; `'POST'` uploads a resource(e.g. image) and give it a unique name then save it's relation with content in database

Thus, I need a progress callback when sending `'POST'` request to `'/contents/id/resType'` because it's an upload. And there may be different type of resources related to different progress displaying ui, so different callbacks needed.

So, I think something like `'resource.get(params, [data], [options])` may be nice. Or I'm using `Resource` in a wrong way.

Thanks.

**Comment by oblogic7** [comment]
I'm running into an issue with passing params for a resource as well.  I've tried to work around the issue that @Nandiin describes, but my solution is not working either.  I'm new to Vue, so I may be doing something completely wrong, but it appears to me that this should work.

`    export default {
        init (context) {
            this.context = context;
        },
        getResource(params) {
            return this.context.$resource('jobs{/id}', params)
        },
        fetchAllJobs(pagination) {
            let params = {
                paginate: pagination.per_page,
                page: pagination.current_page,
                /* additional parameters */
            };

            return this.getResource(params).get({})
        },
        fetchJobById(id) {
            this.resource.get({id: id}).then((response) => {
                return response;
            })
        }
    }`
