### ISSUE TITLE
"Uncaught TypeError: this.http is not a function"

### ISSUE THREAD

**Issue by francescomalatesta** [pagekit/vue-resource#286]
I am getting an error while loading VueResource in a component. Here's the code I used to load it:

```
...
<script>
    import Vue from 'vue'
    import VueResource from 'vue-resource'

    Vue.use(VueResource);

    export default{
...
```

I set up my component by following [this guide here](https://vuejs.org/guide/application.html#Single-File-Components).

This is my webpack config file:

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
    entry: __dirname + '/src/app.js',
    output: { path: __dirname, filename: 'public/js/bundle.js' },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel',
                exclude: /node_modules/
            },
            {
                test: /\.vue$/,
                loader: 'vue',
                exclude: /node_modules/
            }
        ]
    },
    vue: {
        loaders: {
            js: 'babel',
            exclude: /node_modules/
        }
    },
    plugins: [
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        })
    ]
};
```

I am relatively new to js and webpack flow. Don't know if I am missing something. I already tried to call the `http` method in the following ways:
- `this.$http` (I used it before switching to this components);
- `Vue.http`;
- `this.http`;

No one of them is working :( any ideas? If you need any other info let me know :) thanks!

**Comment by mikeyao** [comment]
Try put it In the entry file for webpack: main.js instead of in the .Vue file. 
    import Vue from 'vue'
    import VueResource from 'vue-resource'

    Vue.use(VueResource);
   new Vue({
    el: xx
})



The code above should exist iin where you instantize a Vue instance. 

For example:

**Comment by bmscomp** [comment]
I am facing the same problem I am using the last vue js version 1.0.26 and calling `Vue.use(VueResource);` in the maim.js but no request was triggered
any one has an idea about this issue

**Comment by veksen** [comment]
I'm also having the same issue, running `require` in the webpack entry file (as suggested by @mikeyao)
