### ISSUE TITLE
How do i make a patch request on a specific resource object?

### ISSUE THREAD

**Issue by gbhlwm** [pagekit/vue-resource#306]
in this document:  https://github.com/vuejs/vue-resource/blob/master/docs/resource.md#default-actions

It seems there is no method to make make a patch request.

Should it be one here?

**Comment by clemf** [comment]
It would be great to at least know the reasoning behind PATCH not being included. I think PATCH is much more useful than PUT.

See pull request #313

**Comment by clemf** [comment]
@steffans Any update on this?

**Comment by Sarke** [comment]
This should be in there, it's a fundamental REST verb.  The difference between "replace the resource with this data" (PUT) and "update these values for the resource" (PATCH).

**Comment by gbhlwm** [comment]
@clemf  yes, my purpose is explained by @Sarke perfectly, this is a useful REST verb that cannot get around. So not supporting this method cause much trouble in fact, so please update it.

If you don't see any reason why, then you can say any other reason why not?

**Comment by ausminternet** [comment]
Request #313 still not merged... why?

**Comment by jubinmj5** [comment]
3..3
