### ISSUE TITLE
headers is not available early enough?

### ISSUE THREAD

**Issue by IntellectProductions** [pagekit/vue-resource#315]
I'm using browserify to compile my javascript (Laravel elixir to be exact). I run gulp and it calls browserify.

This is my code:

``` js
var Vue = require('vue');
Vue.config.debug = true
Vue.use(require('vue-resource'));

Vue.http.headers.common['X-CSRF-TOKEN'] = document.querySelector('#token').getAttribute('value');
```

But `Vue.http.headers` is coming back undefined so it can't even set it. Is there a way around this?
Thanks.

**Comment by veksen** [comment]
I'm having the exact same issue, in fact, `Vue.http` is undefined.

**Comment by danielschmitz** [comment]
please try:

```
Vue.http.headers.common['X-CSRF-TOKEN'] = "foo"
```

and re-check Vue.http.headers

tell us the result
