### ISSUE TITLE
uri template

### ISSUE THREAD

**Issue by ericxin1982** [pagekit/vue-resource#321]
Hi,

Sorry to bother you, just want to know how to use external uri template function within the vue-resource, see the source code has this part, but not sure how to use, thanks.

**Comment by wppd** [comment]
`this.$http.put("http://www.test.com{/param1}{/param2}{?page}", {body : "body"}, {params : {param1 : "value1", param2 : "value2", page : "1"}})`

the url will be `http://www.test.com/value1/value2?page=1`

hopefully, this makes sense.
