### ISSUE TITLE
Issue with jsonp method

### ISSUE THREAD

**Issue by bllfrnch** [pagekit/vue-resource#343]
Hi,

I'm having an issue with the jsonp method, and can't figure out what's going on. I have this method defined on a Vue component's methods object (some anonymizing has occurred to protect my client):

```
fetchMoreData: function() {
  this.loading = true;

  var NAMESPACE = window.NAMESPACE = {
    render: _.bind(function(obj) {
      this.$http.post(this.processEndpoint, obj)
          .then(
              function(response) {
                var obj = response.json(),
                    contents = obj.page.content;

                this.appendContents(contents);
                this.loading = false;
              },
              this.handleAjaxError
          );
    }, this)
  };

  this.$http.jsonp(JSONP_URL).then(
      function() {
        console.log('success!', arguments);
      },
      function(response) {
        console.log('jsonp error', response);
      }
  );
}
```

The API I'm hitting doesn't have an option for specifying callback name, so I'm stuck with a response like this:

```
NAMESPACE.render({ /* JSON HERE */ })
```

The JSONP request is submitted, a response is returned, and the function specified in the response is executed. So far, so good. But then the promise reports failure, and I see "jsonp error" in the console. I don't understand why this would be reported as an error when it's clearly succeeding.

Please let me know if I can provide any additional details. Cheers, and thanks for your excellent work!

**Comment by blake-newman** [comment]
@bllfrnch There has been many recent API changes to vue-resource could you confirm that this is still an issue?
