### ISSUE TITLE
params name conflict

### ISSUE THREAD

**Issue by lijiancheng** [pagekit/vue-resource#347]
when a para named length in params , the jsonp request will not work;

Vue.http.jsonp  will send  0=undefined in request, it is error

**Comment by TehJoE** [comment]
I have a similar issue. If the `params` payload for a GET request contains a `length` property, vue-resource tries to place the (probably nonexistent) numeric properties from 0 to `length` in the URL. Renaming the `length` property immediately fixes the issue.
