### ISSUE TITLE
Chinese code errors

### ISSUE THREAD

**Issue by lewis-geek** [pagekit/vue-resource#349]
Use $http.get function , all Chinese character show as question mark  in returned value

Use jQuery Ajax function, returned value are all correct

Sorry for my poor English. Please do me a favor. Thank you!

![2016-08-05 5 43 23](https://cloud.githubusercontent.com/assets/8927407/17432921/67942d00-5b34-11e6-8114-d189a3e76062.png)

**Comment by imakan** [comment]
请问  你这个怎么解决的？

**Comment by lewis-geek** [comment]
@imakan 当时我改用手写 XMLHttpRequest 请求了。这个库已经不维护了 你可以换官方推荐的 axios
