### ISSUE TITLE
弱鸡问个问题

### ISSUE THREAD

**Issue by Eidosper** [pagekit/vue-resource#352]
var registerbox = new Vue({
    el: '.register-box',
    data:{
        name:'',
        email:'',
        password:'',
        passwordagain:'',
        nameerr:'',
        emailerr:'',
        passworderr:'',
        passwordagainerr:'',
    },
    methods:{
        confirm: function () {

```
        this.$http.post('/register',this.data).then(
            (response) =>{
            console.log(response.data)
        articlelist.articles = response.data;
    }).catch(function(response) {
            console.log(response)
        })
    }
}
```

})

我想把这个registerbox的全部data发送到服务器端，有没有优雅的写法？似乎这样写不行，顺便求原因。

**Comment by Eden-Sun** [comment]
vue设计上 this.data 并不是指向你注册的 data
试试 this.$data

**Comment by Eidosper** [comment]
多谢楼上
