### ISSUE TITLE
get 不可以传body有些不方便。

### ISSUE THREAD

**Issue by kyo4311** [pagekit/vue-resource#355]
// in a Vue instance
this.$http.get('/someUrl', [options]).then(successCallback, errorCallback);
this.$http.post('/someUrl', [body], [options]).then(successCallback, errorCallback);

get不能传body，哭死！

**Comment by Eden-Sun** [comment]
看下 #354 ，一样的。

**Comment by kyo4311** [comment]
刚上手vue,看来不是了解的不够深。
