### ISSUE TITLE
Passing data object as params property does not work, plain object works.

### ISSUE THREAD

**Issue by sformisano** [pagekit/vue-resource#357]
Hey all, new to Vue here, but already super excited about it.

I have a get request with parameters, when I pass a plain object as parameter all is good with the world:

```
this.$http.get('endpoint', { params: {'foo': 'bar'} })
```

but if I pass an object from the data property of the app nothing comes through 

```
this.$http.get('endpoint', { params: this.someDataProperty })
```

The modestly ugly workaround I have for now 

```
this.$http.get('endpoint', { params: jQuery.extend({}, this.myDataProperty) })
```

I suspect this has to do with what vue does to its data property for the sake of reactivity and all that, but I would imagine this to be a common way to use a data property?

Thanks

**Comment by sformisano** [comment]
A gentle bump to see if anyone has anything to share on this. Thank you.

**Comment by LinusBorg** [comment]
Can you reproduce this on jsfiddle? This is something probably every user of vue-resource does at some point, and so far there have been no problems with this.
