### ISSUE TITLE
timeout with jsonp

### ISSUE THREAD

**Issue by baby2011** [pagekit/vue-resource#359]
when i use jsonp method with timeout option,it display 'Uncaught TypeError: request.abort is not a function'.

**Comment by blacksunset** [comment]
+1

**Comment by zhe-he** [comment]
+1

**Comment by baby2011** [comment]
这个问题已经解决

**Comment by yhuaqiang** [comment]
请问怎么解决的.可否告知下.yhuaqiang@163.com
