### ISSUE TITLE
Unable to get response in errback

### ISSUE THREAD

**Issue by evanslify** [pagekit/vue-resource#362]
I have a piece of code, like this:

``` js
newCategory(newCategoryName) {
    let url = `${URL_CATEGORIES}/${newCategoryName}`
    this.$http
    .post(url)
    .then(
    (success) => {
        console.log('OK')
    },
    (fail) => {
        console.log('epic fail', fail)
    })
}
```

While the POST request failed with a code (in my case, 409) `fail` would be empty, and even `console.log` wouldn't print anything at all.
I'm trying to get response's HTTP code when a request fails.

**Comment by larsboldt** [comment]
Having same(ish) problem, response object status is 0 even though headers says 401
