### ISSUE TITLE
ProgressEvent Frustrations

### ISSUE THREAD

**Issue by poxin13** [pagekit/vue-resource#375]
For some reason having an issue figuring out how to use this. I have the following code that does appear to work, but it only is updating 'percent' after everything has loaded.

``` javascript
this.$http.get('/apidata', {
    progress: (pe) => {
        this.percent = Math.round((pe.loaded / pe.total)*100);
}}).then((response) => {
    console.log('Success');
    this.apidata = response.data;
}, (response) => {
    console.log('Error');
});
```

this.percent is only being updated after the request finished, which is slightly useless for the intended usage here, any help would be appreciated!

**Comment by lyixuan** [comment]
I have the same question

**Comment by poxin13** [comment]
Still attempting to figure this one out, doesn't appear the code from @steffans on #29 is working either.

**Comment by steffans** [comment]
@poxin13 Can you build and try the latest dev version, i moved adding the progress event listener in my last commit https://github.com/vuejs/vue-resource/commit/b331f93fc7d692b9918223c07cae1b04aee232b0

**Comment by kpihus** [comment]
Hi,

Latest version isn't much better either:

this is how i make request
`      Vue.http.get(path, {
        params: params,
        credentials: true,
        progress: progress
      }).then(//....)`

And progress handler for now is just:
`const progress = (val) => {
  console.log('PROGRESS', val)
}`

but logs will appear after loading is finished.

**Comment by steffans** [comment]
I tested updload progress events with bandwith throttling in Chrome which works. Can you try this as well? Progress events depend on the connection, if i dont use bandwith throttling i only get one or no event.
