### ISSUE TITLE
Can't throw error (reject promise) in response interceptor

### ISSUE THREAD

**Issue by Astray-git** [pagekit/vue-resource#377]
Chrome will throw 'Uncaught (in promise)' if I return reject in response interceptor.`

`when` function takes 3 args: `value, fulfilled, rejected`, but is called with only 2, no rejected callback here:
https://github.com/vuejs/vue-resource/blob/b9c195daca50188f9338d0900654e75fb6eed483/src/http/client/index.js#L40-L46

**Comment by victorwpbastos** [comment]
I'm having this same problem. When using interceptors is there a way to get away with this `Uncaught (in promise)` message in console?

**Comment by steffans** [comment]
Currently it's not implemented that a interceptor can reject a Promise, what would you expect to happen after you returned a rejected Promise?

**Comment by victorwpbastos** [comment]
In fact, I just want to silence the errors in console.

**Comment by floorish** [comment]
@victorwpbastos Just catch the failed promise yourself and return the original response.
Something like this:

```
Vue.http.interceptors.push( (request, next) => {

    // do something with request

    next( response => {

            // will return the original response if the promise fails
            return someRejectedPromise().catch( () => response )

    });

});
```

**Comment by antoniopaisfernandes** [comment]
@steffans It would be great to feed the error to raven-js

Currently using window.onunhandledrejection but it does not have yet browser support. Besides, I also don't like a 'catch all' solution that onunhandledrejection provides.

**Comment by Kaijun** [comment]
I still have no idea how could i perform Error Handling in interceptors... any hacks?

**Comment by tiagomatosweb** [comment]
So do I, I have tried a lot to do a catch all in the interception but no luck at all. 
Does anyone have any clue?

Cheers

**Comment by jarvelov** [comment]
I just created a [pull request](https://github.com/pagekit/vue-resource/pull/621) to let Promise rejections bubble up the chain, this makes it possible to catch the error using the standard `.catch`method. Please support the pull request to add this feature and make vue-resource's error handling easier.
