### ISSUE TITLE
Expecting a function in instanceof check, but got function exec()

### ISSUE THREAD

**Issue by tyaslab** [pagekit/vue-resource#389]
When I use vue-resource version 0.9.3 I found no problem to use it in website and android webview.

But when I upgrade it to 1.0.0 I found error that says "Expecting a function in instanceof check, but got function" but it only occurs in Android WebView and Cordova.

The complete error as shown below,

```
Expecting a function in instanceof check, but got function exec() {
                handler = reqHandlers.pop();
                if (isFunction(handler)) {
                    handler.call(context, request, next);
                } else {
                    warn('Invalid interceptor of type ' + typeof handler + ', must be a function');
                    next();
                }
            }
```

**Comment by Monkey-D-Afei** [comment]
same here...

**Comment by VitaliySmolyakov** [comment]
Hello. 
Same problem with vue-resource v1.0.1 in standart Android browser 4.1.2
Short stack info:
```
TypeError: Expecting a function in instanceof check, but got function 
(resolve) {
    exec() {
    ....
    }
    function next(response) {
    ....
    }
}

at new Promise$1 (vue-resource.js:21:29)
at Client (vue-resource.js:909:16)
at Object.Http (vue-resource.js:1166:12)
at Function.Http. (anonymous function) [as get] (vue-resource.js:1195:20)
```

**Comment by mk-relax** [comment]
This error message is a bit unclear on some platforms (see [here](http://stackoverflow.com/questions/6021245/what-does-this-instanceof-error-message-mean)), but it means that the right hand side of `instanceof` is not a constructor function. 

In your case, check `window.Promise` (line [17](https://github.com/vuejs/vue-resource/blob/1.0.1/dist/vue-resource.js#L17)). It is probably not `undefined` (else it should have been set to the Promise$2 function in line [1509](https://github.com/vuejs/vue-resource/blob/1.0.1/dist/vue-resource.js#L1509)) but also not a constructor function.
