### ISSUE TITLE
cant modify jsonp callback function's name

### ISSUE THREAD

**Issue by yuu2lee4** [pagekit/vue-resource#393]
i want modify it

**Comment by afshinpersian** [comment]
same problem

**Comment by yuu2lee4** [comment]
@afshinpersian   i found a param 'jsonp' which can define the callback function's name , but not be listed in document

**Comment by afshinpersian** [comment]
@yuu2lee4 hi, what is that . I have handled it by webpack devserver proxy ! without jsonp

**Comment by steffans** [comment]
See #477

**Comment by yuu2lee4** [comment]
@steffans   i used 'jsonp' very well in 1.0.3. when i update to 1.2.0, it dont work.I just want modify callback's key name,not value(function) name.mhy code:
![image](https://cloud.githubusercontent.com/assets/8046366/22912604/46c48a98-f2a1-11e6-9e62-244087ca2885.png)

**Comment by steffans** [comment]
A function called `Vue.fetch` is not available in vue-resource ?

**Comment by yuu2lee4** [comment]
sorry, it is based on vue-resource:
![image](https://cloud.githubusercontent.com/assets/8046366/22924004/7dfc1ae8-f2de-11e6-8a8e-c65db8cd3648.png)
