### ISSUE TITLE
timeout callback

### ISSUE THREAD

**Issue by xdadda** [pagekit/vue-resource#403]
Hi guys

I was wondering if it would be possibile to implement a timeout callback, similar to that already implemented for "before" and "progress"

User case: need to hide a loader modal if connection times out

Current workaround for me is
`this.$http.get('https://google.com:82', {
    timeout: 3000, 
    before: (xhr) => { 
        this.timeout = setTimeout( () => {
            //handle timeout
        }, xhr.timeout);
          }
    }).then((response) => {
              // success callback
              clearTimeout(this.timeout);
    }, (response) => {
              // error callback
})`

**Comment by ideaterminal** [comment]
@steffans Is there a plan to implement this feature? If so, I will submit a pull request.

**Comment by michaellyu** [comment]
https://github.com/pagekit/vue-resource/blob/master/src/http/client/xhr.js#L27
https://github.com/pagekit/vue-resource/blob/master/src/http/interceptor/timeout.js#L11

Can't working!
```javascript
Loading.show();
Vue.http.get('/fetch', {
  timeout: 10 * 1000,
})
.then(() => {})
.catch(() => {
  // can't catch timeout
})
.finally(() => {
  // can't catch timeout
  Loading.hide();
});
```

**Comment by standup75** [comment]
+1

**Comment by steffans** [comment]
Add in v1.1.0, abort/timeout request resolve to an error with a status: 0
