### ISSUE TITLE
jsonRPC supports

### ISSUE THREAD

**Issue by maxwell-git** [pagekit/vue-resource#409]
is there any way to supports jsonRPC ?

**Comment by vercha** [comment]
does it support jsonrpc now?

**Comment by maxwell-git** [comment]
@vercha jsonrpc only a protocol of RPC request. It doesn't matter to vuejs.

**Comment by vercha** [comment]
well, I'm asked to request server with jsonrpc, is it possible with vue-resource?  how to make it?
thanks very much!
