### ISSUE TITLE
Adding an "after" callback

### ISSUE THREAD

**Issue by Grafikart** [pagekit/vue-resource#414]
Interceptors are a nice way to add some behaviours before and after a Request. But there is no way to do the same thing for a single resource. There is a callback `before` wich is nice to display a loader but there is no `after` callback :(

The idea would be to clone https://github.com/vuejs/vue-resource/blob/master/src/http/interceptor/before.js giving the response as a callback. 

I can do the PR myself but I want to know if it would be accepted. Maybe you think people should use their own `after` interceptor.

**Comment by berwin** [comment]
I have the same question

**Comment by Grafikart** [comment]
If you need it you can create your own interceptor 

```
export default function (request, next) {

    next((response) => {
        if (request.after) {
            request.after.call(this, request);
        }
    })
}
```

**Comment by steffans** [comment]
Would the `after` callback normally happen in `.then(response)` ?

**Comment by berwin** [comment]
@steffans But it  can  not  be  unified intercepted

**Comment by berwin** [comment]
@steffans Sorry, it turns out that interceptors can meet my needs 😂😂😂

**Comment by leixu2txtek** [comment]
@Grafikart Where this code is placed ? thx.

**Comment by HcySunYang** [comment]
@Grafikart I think we still need `after` hook is better, so that we can write a unified mixins:
```js
// mixins
export default {
  http: {
    root: '/mfepro/kuailv/mobile-mall',
    before: function (request) {
      if (this.previousRequest) {
        this.previousRequest.abort()
      }
      this.previousRequest = request

      // Show loading animation
      this.isShowLoading = true
    },
    alert: function () {
      // Hide loading animation
      this.isShowLoading = false
    }
  }
}
```

**Comment by bentarik** [comment]
@leixu2txtek  you can add it in the main.js like this 

` Vue.http.interceptors.push((request, next) => {
  next((response) => {
    if (request.after) {
      request.after.call(this, response)
    }
  })
}) ` 

or create a function like this in the vue-resource.esm.js

`/**
 * After Interceptor.
 */

function after (request, next) {
  next((response) => {
    if (isFunction(request.after)) {

      request.after.call(this, request);
    }

  })
}`

**Comment by bentarik** [comment]
@leixu2txtek you can add it in the main.js like this

Vue.http.interceptors.push((request, next) => { next((response) => { if (request.after) { request.after.call(this, response) } }) })

or create a function like this in the vue-resource.esm.js

`function after (request, next) {
next((response) => {
if (isFunction(request.after)) {
  request.after.call(this, request);}})}
`

**Comment by bentarik** [comment]
> function after (request, next) { next((response) => { if (isFunction(request.after)) { request.after.call(this, request);}})}
