### ISSUE TITLE
uc手机浏览器请求无反应

### ISSUE THREAD

**Issue by WoJoinGitHub** [pagekit/vue-resource#432]
uc手机浏览器请求无反应，使用vue_resource的项目白屏，因为请求无反应，阻塞了进程。

**Comment by viko16** [comment]
+1

**Comment by dp199313** [comment]
+1

**Comment by slashhuang** [comment]
+1

**Comment by chengzhuotc** [comment]
这个问题有人解决没有啊，我也遇到了

**Comment by chengzhuotc** [comment]
这个问题我的解决方法是降低了版本
![image](https://cloud.githubusercontent.com/assets/9107399/19336282/875c2942-913c-11e6-8e31-471d5a0aba91.png)

**Comment by wuxiaolinchn** [comment]
我在v1.0.3中遇到请求阻塞问题，平台是Android，浏览器是UC浏览器
