### ISSUE TITLE
request.abort is undefined

### ISSUE THREAD

**Issue by ecmel** [pagekit/vue-resource#434]
request.abort function is undefined in before hook and interceptors when using created resources.

**Comment by fntneves** [comment]
+1

**Comment by yhuaqiang** [comment]
yes, when using jsonp, the jsonp client do not declare a method named abort, other clients do. please fix it...

**Comment by luqingxuan** [comment]
it seems that vue-resource uses promise, not ajax, ajax has method abort and it works,
but promise has no abort method, so u can not be able to stop it
