### ISSUE TITLE
documentation: JSONP and Cross domain requests

### ISSUE THREAD

**Issue by lensgolda** [pagekit/vue-resource#44]
It would be nice to add an example to documentation with cross domain request and how to get data from response properly. Because this topic raises many questions. Thanks.

**Comment by intositeme** [comment]
Yes. the documentation is lacking.

**Comment by ernysans** [comment]
+1 This is one of the most important reasons why I haven't be able to fully migrate to vue. I'm trying to develop an api but I can't properly access the data, the get method is not good because makes a new session every time and I need to retrieve specific data from the logged user. I'm stuck. There is some old examples going around but doesn't work with the latest version. Please help.

**Comment by infernobass7** [comment]
Agreed more documentation would be nice.

**Comment by uwe** [comment]
I got it working by this:

`Vue.http.options.xhr = {withCredentials: true};`

**Comment by YerkoPalma** [comment]
I opened an issue about the lack of documentation (#244). What would you like to include in the docs?

**Comment by ak04nv** [comment]
Hm...
I've got the error `Request header field Content-Type is not allowed by Access-Control-Allow-Headers`
Acording to this [post](http://stackoverflow.com/a/30554385), may be default setting application/json for Content-Type field header for cors requests is not good idea?

**Comment by Rachelin** [comment]
@ak04nv  Yes!!
I also met this problem too.

**Comment by stephanedemotte** [comment]
+1

**Comment by Townfolio** [comment]
I believe the correct way of doing this going forward is actually this...

```
Vue.http.options.credentials = true;
```

**Comment by aios** [comment]
CORS cookies dont sended with that options.

**Comment by Shidou** [comment]
Vue.http.options.xhr = {withCredentials: true};
Vue.http.options.emulateJSON = true;

on vuejs2.0 to solve ‘post’ request。

**Comment by gkatsanos** [comment]
can't figure out how to do JSONP request.. please add an example..

**Comment by raphcadiz** [comment]
@townfolio sorry I'm so noob on vue, where exactly do set that?. I have this main js from the web-pack

**Comment by gkatsanos** [comment]
@raphcadiz you should not use vue-resource but rather switch to an external Promises library or use native `window.fetch`. https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4#.4nk3rlhn9

**Comment by qianthinkover** [comment]
Did anybody to solve this problem?

**Comment by ak04nv** [comment]
@qianthinkover did you read my comment above?
