### ISSUE TITLE
XMLHttpRequest.responseType is always set to 'blob'

### ISSUE THREAD

**Issue by dubov94** [pagekit/vue-resource#440]
https://github.com/vuejs/vue-resource/commit/2cc37e8c57ba37c85d9cbf4fe190018a5c320b77#diff-948a9196ffabd69921c15521940d9d73R54

I think this condition is always true, thus you always do reset the responseType to 'blob' and break parsing logics.

**Comment by steffans** [comment]
No IE9 & 10 don't support responseType on XHR. What breaks the parsing logic ?

**Comment by dubov94** [comment]
For example if I use [sinon](sinonjs.org) for faking XMLHttpRequest it [relies](https://github.com/sinonjs/sinon/blob/master/lib/sinon/util/fake_xml_http_request.js#L312) on the value of responseType.
