### ISSUE TITLE
Can't input zero in number field

### ISSUE THREAD

**Issue by arkeds** [pagekit/vue-resource#448]
I can't input zero as the first number in the number field. This happens when I put the vue-resource cdn after the vue.js file. If I enter 0 then a non zero number next, it removes the 0.

Here is the CDN that I used for the vue-resource.
[https://cdn.jsdelivr.net/vue.resource/1.0.3/vue-resource.min.js](url)

**Comment by andreixk** [comment]
I believe it's a javascript/math concept: any zero prefixes of a number are ignored. you would have to set the field as a string in order to get the leading zero, or convert it through computed property.
