### ISSUE TITLE
Error after updating to ver 1.0.3

### ISSUE THREAD

**Issue by dfk7677** [pagekit/vue-resource#451]
I am using the prebuild package of vue with laravel 5.3. When using vue-resource 0.9.3 everything works ok. If I update to 1.0.3 I get the following error: `TypeError: Cannot read property 'replace' of null`. Also the error seems to be happening in the trim function inside the Headers.set function.

Some sample code I am using:
`this.$http.get('api/users', {params: {token: this.auth}}).then((users) => {this.$set('users', users.data);});`

All the requests are made from inside vue components and I get an error for each an every http request.

My package.json file:
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-9",
    "laravel-elixir-vue": "^0.1.8",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.14.0",
    "vue": "^1.0.28",
    "vue-resource": "^1.0.3",
    "vue-validator": "^2.1.7"
  }
}

Am I doing something wrong or the new version is not combatible with laravel-elixir-webpack package?

**Comment by kubacode** [comment]
I'm also receiving this error. Does anyone have any thoughts as to what could be going on?

**Comment by Zwaen91** [comment]
+1

**Comment by dmurtari** [comment]
I was seeing the same error message, and it turned out to be because I was trying to set the Auth header to be null. Not sure if yours would be the same cause, but thought I'd mention it.

**Comment by steffans** [comment]
Fixed in v1.1.0+
