### ISSUE TITLE
Could you tell me how to handle this error?

### ISSUE THREAD

**Issue by zhongs** [pagekit/vue-resource#454]
XMLHttpRequest cannot load http://192.168.10.47:20005/nxn/api/init. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.10.118:8080' is therefore not allowed access.

"vue-resource": "^1.0.3",

**Comment by nblackburn** [comment]
You need to enable cors on the server as your browser blocks the request for security reasons.
