### ISSUE TITLE
http response did not parse JSON object in body in IE9

### ISSUE THREAD

**Issue by Nununene** [pagekit/vue-resource#458]
Vue resource version : vue-resource@1.0.3

Request respond header Content-Type is "application/json; charset=UTF-8"
but In IE9 it still left as string

(it works fine in IE11/Firefox/Chrome)

```
Vue.http.get(server + '/login?user=foo').then(
  (response) => {
    // Server is up, response got
    console.log(typeof response);
    console.log(typeof response.body);
    console.log(response.body);
    console.log(JSON.stringify(response.body));
  },
```

in IE11/Firefox/Chrome shows

```
object
object
Object { some data here }
{"user_id":"....
```

in IE9 shows

```
object
string
{"user_id":"....
{\"user_id\":\"\"......
```

UPDATE:
In IE9 using XDomain client, seems not return with headers(or simply 'Content-Type') to
request.respondWith

```
// Temporary fix for IE9 (http/client/xdr.js line 19)
var headers = {};
headers['Content-Type'] = xdr.contentType;
resolve(request.respondWith(xdr.responseText, {status, headers}));
```

**Comment by otiagovicente** [comment]
gurizada, tem que colocar o tipo de conteúdo que vocês estão mandando. Pq senão é zica na certa moleque, é chute em tatu, é vc estar namorando aquela menina sem ela saber. passa no header lá :

Accept application/json

n sejam guri, sejam canhoto

**Comment by otiagovicente** [comment]
Content-Type  caralho a 4 guerê guerê
