### ISSUE TITLE
After login change default options

### ISSUE THREAD

**Issue by sonic182** [pagekit/vue-resource#459]
Hi, I'm trying to set a global header after login on my app. I've tried passing Vue object to my auth service and doing 

``` javascript
// login component...
// after retrive token...
Vue.http.headers.common['Authorization'] = `Bearer ${token}`
// other component after login...
this.$http.get('resource') // unauthorized
```

but doesn't set the value globaly.

**Comment by 016** [comment]
I also want to know how to do this kind dynamic global level header change.


right now all I can do is write a new action to send request call(get, post) and set header as option in it.

it's a little pain, and definitely what I want, so can anyone help with how to change global header in component  via this$http.xxxx 

thx.

**Comment by 016** [comment]
@sonic182 

this is working for me

login.vue
`
import Vue from 'vue';


.....


Vue.http.headers.common['X-CSRF-TOKEN'] = '1234'
`

of cause you need make sure that X-CSRF-TOKEN is allow by you api's CORS's Access-Control-Allow-Headers

good luck.

**Comment by sonic182** [comment]
Mmmm well I changed my focus and used Vuex to set the header in every request with a injector and a JavaScript variable over Vuex, works pretty well
