### ISSUE TITLE
POST not getting data but $.ajax does.

### ISSUE THREAD

**Issue by ivandoric** [pagekit/vue-resource#460]
Maybe this is the problem with my understanding of Vue resource, but why does this work:

```
_this = this;

            $.ajax({
                type: 'POST',
                url: requestURL,
                async: false,
                success: function (data) {
                    _this.$set('cartData', data);
                }
            });
```

But this does not:

```
this.$http.post(requestURL).then(function(response){
        this.$set('cartData', data);
})
```

I get a "Headers already sent error". Backend for this example is Symfony 2.

**Comment by NewRasputin** [comment]
It looks like you are passing the `response` object to your callback but trying to set `cartData` to the `data` object. Try `this.$set('cartData', response);`

**Comment by ivandoric** [comment]
Nope, there was a typo in my example. I did try to set `response` to be `cartData`, tried it again just now. Still getting "Failed to start the session because headers have already been sent by "" at line 0." but with `$.ajax` it still works.

**Comment by NewRasputin** [comment]
Could you post the whole component code?

**Comment by evertramos** [comment]
Have you tried a simple:

`this.cartData = data;`

**Comment by ivandoric** [comment]
@evertramos I think I did, but it was a long time ago. the project is finished, so I can't check it now. But thanks for the suggestion.
