### ISSUE TITLE
jsonp can't not get response headers????????

### ISSUE THREAD

**Issue by ringcrl** [pagekit/vue-resource#464]
When i try 

```
this.$http.jsonp('myurl').then((response) => {
console.log(response.headers.get('Expires'))
console.log(response.headers.get('Date'))
....
})
```

i see 

```
null
null
```

**Comment by ringcrl** [comment]
<img width="457" alt="qq20161017-0 2x" src="https://cloud.githubusercontent.com/assets/16740021/19434409/d435a104-9497-11e6-8bd6-66b2f1924513.png">

**Comment by gkatsanos** [comment]
same problem here

**Comment by steffans** [comment]
Only XHR's request have response headers, not JSONP. You have to make a CORS request instead.
