### ISSUE TITLE
Is vue-resource fully supported by Vue 2?

### ISSUE THREAD

**Issue by ricardodantas** [pagekit/vue-resource#466]
Hi,

I didn't found a compatibility information with Vue 2 anywhere on documentation. So, is it possible to use vue-resource fully with Vue 2?

Thanks.

**Comment by haycco** [comment]
@ricardodantas I have the same trouble, vue-resource 1.0.3 version didn't working with vue 2.0.3...

**Comment by Smallpath** [comment]
It supports vue2.0 except the SSR part

**Comment by CinKon** [comment]
I have to extend our project with SSR JUST BECAUSE we load content from a REST API with Vue-Resource 🗡 
After hours i find this issue. 💯 
Will there be SSR Support anytime?

**Comment by steffans** [comment]
Feature added in v1.2.0
