### ISSUE TITLE
Can I catch jsonp req error?

### ISSUE THREAD

**Issue by Gavin-Gong** [pagekit/vue-resource#469]
```
      getSearchData () {
        this.$http.jsonp(url).then(res => {
          console.log(res.data) // can't reach here
        }).catch(err => {
          console.info(err) // can't reach here
        })
      }
```

When jsonp request fail, `catch` can't get err info. I also find  `jsonp` request has been changed to `get` request
![image](https://cloud.githubusercontent.com/assets/9414378/19679450/58fe5d1c-9ad4-11e6-99ec-c8b17e0fcfdd.png)

**Comment by shakee93** [comment]
**same problem over here. how am i supposed to get rid of this error ? any idea ?** 

![image](https://cloud.githubusercontent.com/assets/14835725/19726678/b135e394-9ba9-11e6-8157-685d9a846936.png)

**Comment by ICTlight** [comment]
Have you find some methods to deal this?

**Comment by gkatsanos** [comment]
Same problem here.

**Comment by benjides** [comment]
Calling the `GET` method and passing the JSONP callback name as a parameter seems to do the trick for me.
Here is a working example:
```
Vue.http.get('api', {
      params: {
        callback: 'callback'
      }
    })
    .then((response) => {
      console.log(response.data)
    })
```
Note it does not matter the callback name as the library would parse it automatically into a JSON object.

**Comment by chinafootballyu** [comment]
Same problem here. When I close the network!  I can't catch the error.

**Comment by chinafootballyu** [comment]
Same problem here. When I close the network!  I can't catch the error.
