### ISSUE TITLE
Can't send body with a GET request

### ISSUE THREAD

**Issue by wb9688** [pagekit/vue-resource#471]
Why is it impossible to send a body with a GET request?

**Comment by xiongxliu** [comment]
You can do this: Vue.http.get(option.url,{params: { url:url }}).then((response)=>{}).

**Comment by xiongxliu** [comment]
You can try: Vue.http.get(option.url,{params: { name:"jack" }}).then((response)=>{});

**Comment by wb9688** [comment]
@xiongxliu: But that's for sending URL parameters, not for sending a body…

**Comment by jrood** [comment]
To the question of "why" I think [this](http://stackoverflow.com/a/983458/3390298) is a good response.

**Comment by Autumnwater** [comment]
i meet it,too
my code:
$http.post(common.api_base_url,{api:'checkPhoneNumber'},{
		headers:{
			'KA-Sign':'headopp',
		}
	}).then(=>{})

and it get '{"api":"checkPhoneNumber"}' be a key ....no vale...

if you send $http.post(common.api_base_url,{},{})
it get '{}' be a key

**Comment by Autumnwater** [comment]
ok
wo find it 
https://github.com/yyx990803/vue-resource/issues/461
 thanks resmall

**Comment by YamiOdymel** [comment]
GET has no `body` but params.

GET uses URL params AS its body.
