### ISSUE TITLE
vue-resource支持vue2.0吗？

### ISSUE THREAD

**Issue by nieyulin112** [pagekit/vue-resource#478]
你好,现在的vue－resource支持vue2.0吗？如果支持，相对vue1.0做了什么变化？谢谢

**Comment by AnsonHwang86** [comment]
https://github.com/vuejs/vue-resource/issues/466

**Comment by AnsonHwang86** [comment]
@nieyulin112 除了SSR部分，都支持的 https://github.com/vuejs/vue-resource/issues/466
