### ISSUE TITLE
interceptors 里怎么停止return response

### ISSUE THREAD

**Issue by zhangman8667** [pagekit/vue-resource#480]
Vue.http.interceptors.push((request, next) => {

  // modify request ...

  // stop and return response
  next(request.respondWith(body, {
    status: 404,
    statusText: 'Not found'
  }));
});
场景：遇到公共的错误，处理完之后，就停止给$http函数回调，上面的方法貌似不行
Vue.http.interceptors.push((request, next) => {
  // ...
  // 请求发送前的处理逻辑
  // ...

  next((response) => {
    console.log(response)
    if (response.data.code === 1) {
      response.data = response.data.data
    } else {
         if (response.data && response.data.message) {
        Notifiy('错误', response.data.message, 'error')
      } else {
        Notifiy('错误', '请求出错', 'error')
      }
// 想在这里停止返回response
     }
  })
})

**Comment by jimczj** [comment]
我也遇到这个问题，可是没人回答

**Comment by jimczj** [comment]
好吧，我自己半解决了这个问题，直接return 一个东西，相当于把异常抛出
`next((response) => {
if (response.data.code === 1) {
  response.data = response.data.data
} else {
  if (response.data && response.data.message) {
    Notifiy('错误', response.data.message, 'error')
  } else {
   Notifiy('错误', '请求出错', 'error')
  }
  return response// 想在这里停止返回response，可以直接 return response，这样catch会执行，但then不会执行
}
})`

**Comment by zhangman8667** [comment]
是的，想在interceptors这里面处理公共的错误，不想在每个请求里面加catch，我的单个请求只处理了then

**Comment by hedanto** [comment]
可以直接 return {...response.body, ok: false};

**Comment by qpxtWhite** [comment]
if return {...response.body, ok: true}, then I need to check the data in each request method;
if return {...response.body, ok: false}, then I need to add catch in each request method, otherwise the browser will throw en error!!!!!!!!

有啥更好的办法不？

**Comment by catalsdevelop** [comment]
你可以直接返回一个Promise.reject()，像这样
```js
next(function(response) {
  if (response.data.err_code === 1) {
    // global error tracking
    doSomething()
    return Promise.reject()
  }
  return response
})
```
这个rejection如果你不在实例中catch的话，最后会被浏览器打印出来，但是确实可以阻止then的进一步执行。在1.3.3之前，这个rejection并不能被instance.$http.get(url).then().catch()的catch捕获，1.3.4已经修复了这个问题。#377 #621   @zhangman8667  @qpxtWhite
