### ISSUE TITLE
Does vue-resource have a hard dependency on Vue?

### ISSUE THREAD

**Issue by brycepj** [pagekit/vue-resource#484]
As far as I can tell, the [VueResource service is also exposed at `window.VueResource`](https://github.com/yyx990803/vue-resource/blob/master/dist/vue-resource.js#L10), but I'm trying to figure out if it's possible to use `resource` and/or the one-off http methods when Vue isn't loaded.

**Comment by steffans** [comment]
Sorry, there are some dependencies which have to be refactored to make this work standalone.
