### ISSUE TITLE
Setting options in Vue component instantiation doesn't seem to work

### ISSUE THREAD

**Issue by chlab** [pagekit/vue-resource#487]
It's stated [here](https://github.com/pagekit/vue-resource/blob/master/docs/config.md#configuration) that passing options in the Vue component options is the same as configuring them using the global configuration. This doesn't work for me:

```javascript
new Vue({
  http: {
    root: '/api'
  }
})
```

this also doesn't work:

```javascript
new Vue({
  http: {
    options: {
      root: '/api'
    }
  }
})
```

However, this does:

```javascript
Vue.http.options.root = '/api';
```

**Comment by zhu** [comment]
https://github.com/pagekit/vue-resource/blob/master/src/index.js#L34
I think `this.$options.http` should change to `this.$root.$options.http` in Vue 2.

**Comment by websanova** [comment]
Why is this closed?

Seems to still be an issue.
