### ISSUE TITLE
how handler  500 ？

### ISSUE THREAD

**Issue by docikaci** [pagekit/vue-resource#489]
![image](https://cloud.githubusercontent.com/assets/7788102/20036136/ac13ae94-a439-11e6-8592-ba806aebf072.png)

alert 323  not work!!
thanks

**Comment by gotraveltoworld** [comment]
You can see this example [Example](http://www.cnblogs.com/keepfool/p/5657065.html).
If you want to check different http status code to look below source code.
```Javascript
Vue.http.interceptors.push((request, next) => {
    next((response) => {
        console.log(response.status); // 404 , 500 ...
    });
});
```
Attention the next() function only one parameter, so you can't set two parameters.
See [vue-resource, http/client](https://github.com/pagekit/vue-resource/blob/develop/src/http/client/index.js)
