### ISSUE TITLE
Response didn't get parsed JSON object in X5(we-chat browser)

### ISSUE THREAD

**Issue by lsvih** [pagekit/vue-resource#490]
It has some wrong with those browsers.I can get the JSON object in chrome,firefox and newest IE,but I get "string" in older IE and wechat browser.

**Comment by raphaelsoul** [comment]
similiar problem: 

Browser: Chrome
Prod env: LNMP & https schema. Got output below via `console.log(response)`
![image](https://cloud.githubusercontent.com/assets/8615787/20055985/dd7a1050-a51e-11e6-82f9-2a1333b8d6e9.png)

Local env: LNMP & http schema but works well. It also works before I deploy SSL cert in Prod env. 
I am quite sure, that the content negotiation is right. 
Weired.

**Comment by lsvih** [comment]
@raphaelsoul 
Now I have used axios to replace it.
[Axios](https://github.com/mzabriskie/axios) is easy to use,its usage is similar to this lib.

**Comment by AlexCW** [comment]
Also had this issue when migrating a site which was making requests on the same subdomain to a different domain.

The above fix worked with the interceptor but it would be nice to diagnose what is actually going wrong.

As above it just happens in https chrome, but works in all other browsers and non secure chrome.

**Comment by steffans** [comment]
Please try the latest v1.2.0
