### ISSUE TITLE
About Http2

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [pagekit/vue-resource#491]
Http2 use lower case key like "content-type",but vue-resource only examine upper case key like “Content-Type” 
function body (request, next) {

        if (request.emulateJSON && isPlainObject(request.body)) {
            request.body = Url.params(request.body);
            request.headers['Content-Type'] = 'application/x-www-form-urlencoded';
        _}_

        if (isFormData(request.body)) {
            delete request.headers['Content-Type'];
        }

        if (isPlainObject(request.body)) {
            request.body = JSON.stringify(request.body);
        }

        next(function (response) {

            var contentType = response.headers['Content-Type'];

            if (isString(contentType) && contentType.indexOf('application/json') === 0) {

                try {
                    response.data = response.json();
                } catch (e) {
                    response.data = null;
                }
            } else {
                response.data = response.text();
            }
        });
    }

**Comment by steffans** [comment]
This was fixed in [1.0.1](https://github.com/pagekit/vue-resource/releases/tag/1.0.1)
