### ISSUE TITLE
can not customize jsonp callback name

### ISSUE THREAD

**Issue by sevencai** [pagekit/vue-resource#493]
I'm trying to send a jsonp request, but I find that I can not  customize the jsonp callback name.  

After reading  the source code , I found that the callback name has been written to be fixed.

`callback = '_jsonp' + Math.random().toString(36).substr(2),`  
// in vue-resource.common.js line 892

Isn't it a better way for developers to customize it through passing a parameter ? 

Thanks for reading.

**Comment by benjides** [comment]
Instead of calling the jsonp method use the `GET` one and pass the jsonp name callback as a parameter.
Here is a working example:
```
Vue.http.get('api', {
      params: {
        callback: 'callback'
      }
    })
    .then((response) => {
      console.log(response.data)
    })
```
It does not matter the callback name as the library would parse it automatically into a JSON object.

**Comment by steffans** [comment]
See #477
