### ISSUE TITLE
Issue with IE 11 '=>'

### ISSUE THREAD

**Issue by grelu** [pagekit/vue-resource#498]
Hi,

excuse my english.

I have an issue with IE 11 and this : 

`resource.save(
					{'idQuestionnaire' : this.idQuestionnaire,'idRootnode' : this.idRootnode,'newResponses' : JSON.stringify(this.newResponses)}
					).then((datas) => {
						if(datas == "NOK") {
							vuealert.vuemessage="Problem with your save"
							vuealert.danger=true
							return
						}else{
							vuealert.vuemessage="Updated !"
							vuealert.success=true
							this.newResponses=[]
							this.questionanswer=datas
							this.checkSubChapterOrNot()
							//console.log(this.questionanswer)
						}
					},(datas) => {
						
					}
					);`

The bug is a problem with IE or vue-resource ?
i do call the method 'save' with deprecated method for IE ?

Thanks

**Comment by chrisforrence** [comment]
Those look like [arrow functions][1], which are part of ES6 and unsupported in IE. Your choices will be either to replace them with conventional function definitions or use something like [Babel][2] to convert ES6 syntax.

    // Replace something like
    (datas) => { ... }

    // with
    function(datas) { ... }

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
[2]: http://babeljs.io/

**Comment by grelu** [comment]
Thank you very much.
I close this post. Bye !
