### ISSUE TITLE
meta support for request

### ISSUE THREAD

**Issue by aguegu** [pagekit/vue-resource#499]
It would be nice to send some arguments with the request to the interceptors, without sending to the backend api. So in the response section of the interceptor can determine its behavior.

**Comment by audiolion** [comment]
could you give an example code snippet for what you would want this to look like / the use case as compared to how you would do it now.

**Comment by aguegu** [comment]
```
Vue.http.interceptors.push((request, next) => {
  if (request.url === 'login') {
    next();
  } else {
    request.headers.set('Authorization', `JWT ${store.state.account.token}`);

    next((response) => {
      if (response.status === 401) {
          app.$router.push({ name: 'signin' });
      } elseif (response.status === 400) {
          if (!request.meta.mute) {
              alert('bad inputs: ' + response.data.message);        
         }
      }
      return response;
    });
  }
});
```

`alert` can cover most of the scenarios, while there may be some cases where I would like to handle the bad inputs manually.

**Comment by aguegu** [comment]
It seems that, I can just append the meta field in `options`. close for now.
