### ISSUE TITLE
Why not make Promise an external library

### ISSUE THREAD

**Issue by wonderbeyond** [pagekit/vue-resource#503]
I saw `Promise` was implemented in `src/lib/promise.js`, but why not make it an dependent module?

Because we've probably already depend on a `Promise` polyfill,  Two `Promise` implementation will be  bundled together if `vue-resource` is used.

**Comment by reverland** [comment]
maybe peerdepdency？

**Comment by wonderbeyond** [comment]
A normal dependency of one popular Promise implementation is enough.

**Comment by steffans** [comment]
The Promise polyfill will be removed in v2.0
