### ISSUE TITLE
Is there timeout callback or complete(whether success or not) callback?

### ISSUE THREAD

**Issue by forzalianjunting** [pagekit/vue-resource#504]
thank you very much!

**Comment by KirkOlson** [comment]
I have the same problem. A timeout gives back an empty response with only the 'ok' property set to false. Is there a way to find out there was a timeout?

**Comment by joexanderson** [comment]
@forzalianjunting @KirkOlson You guys might want to add discussion to #403 so we can keep everything in one issue.

**Comment by steffans** [comment]
Add in v1.1.0, abort/timeout request resolve to an error with a status: 0
