### ISSUE TITLE
请问如何abort()未完成的请求？

### ISSUE THREAD

**Issue by EosPeng** [pagekit/vue-resource#505]
有时候一些操作会导致在请求相同的内容时，发送多个http请求。

我该如何终止之前某一个未完成的http请求？

**Comment by topul** [comment]
Abort a previous request when a new request is about to be sent. For example when typing in a autocomplete input.

```
{
  // GET /someUrl
  this.$http.get('/someUrl', {

    // use before callback
    before(request) {

      // abort previous request, if exists
      if (this.previousRequest) {
        this.previousRequest.abort();
      }

      // set previous request on Vue instance
      this.previousRequest = request;
    }

  }).then((response) => {
    // success callback
  }, (response) => {
    // error callback
  });
}
```

**Comment by yihuaxiang** [comment]
> Abort a previous request when a new request is about to be sent. For example when typing in a autocomplete input.
> 
> ```
> {
>   // GET /someUrl
>   this.$http.get('/someUrl', {
> 
>     // use before callback
>     before(request) {
> 
>       // abort previous request, if exists
>       if (this.previousRequest) {
>         this.previousRequest.abort();
>       }
> 
>       // set previous request on Vue instance
>       this.previousRequest = request;
>     }
> 
>   }).then((response) => {
>     // success callback
>   }, (response) => {
>     // error callback
>   });
> }
> ```

取消后会执行 error callback ，有办法呢判断到底是报错还是取消吗？（取消后不希望执行 error callback） 谢谢啦
