### ISSUE TITLE
header 怎么加Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by zhangman8667** [pagekit/vue-resource#506]

**Comment by mysqlite** [comment]
header里面的Access-Control-Allow-Origin是服务器加的，详情请参考：
[跨域资源共享 CORS 详解](http://www.ruanyifeng.com/blog/2016/04/cors.html)
[服务器端解决跨域问题的三种方法](http://blog.csdn.net/james_wade63/article/details/50772041)
