### ISSUE TITLE
How can i use response.json() method as it returns a promise via 1.0.0

### ISSUE THREAD

**Issue by MungBeanSoup** [pagekit/vue-resource#508]
> Changed Response methods text(), json() and blob() to return a Promise.

How can i use it to parse Json data.

Sorry for my poor English.

**Comment by nddery** [comment]
You can chain the `.then` calls, as long as you return a Promise (which is what `response.json()` returns). [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#Chaining) probably explains it better than me.

```js
this.$http.get('/someUrl')
  .then(response => response.json())
  .then(json => {
    // success callback, `json` is the JSON
  })
```

**Comment by MungBeanSoup** [comment]
In that way,how can I pre-deal all response in my application.
I want to parse response and handle some err code in one place.
I trend to use 'interceptors', but if response.json() return a promise, i dont know how to return the parsed object.
Besides,each request has 2 'then' looks complex and redundancy.

**Comment by reverland** [comment]
@MungBeanSoup 
https://github.com/pagekit/vue-resource/blob/master/src/promise.js

**Comment by steffans** [comment]
@MungBeanSoup You can also use `response.body` which provides the parsed body object or string.
