### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by mealinks** [pagekit/vue-resource#509]
vue-resource 1.0.3 is throwing an error every time i tried to access any api routes, also the package name laravel/passport have the same issue, when i try to load their components those errors are thrown  :

```
TypeError: Cannot read property 'set' of undefined
Uncaught (in promise) TypeError: Cannot read property 'set' of undefined
...
```

those errors appears regarding this change :

`request.headers['X-CSRF-TOKEN'] = Laravel.csrfToken;`
_everything goes right with that syntax._
 to 
`request.Headers.set('X-CSRF-TOKEN', Laravel.csrfToken)`
_so here where i got the error._

 but before that change I got this : `TokenMismatchException in VerifyCsrfToken 68:`

**Comment by peterrecore** [comment]
Are your code samples cut and paste exactly from your code?  You have **H**eaders in one and **h**eaders in the other (capital H vs lowercase H).
