### ISSUE TITLE
Plus char not encoded with emulateJSON set to true

### ISSUE THREAD

**Issue by j-a-p-dev** [pagekit/vue-resource#51]
I have following global config : 

``` js
Vue.http.headers.common['X-CSRF-TOKEN'] = document.getElementById('csrf_token').getAttribute('content');
Vue.http.options.emulateJSON = true;
```

I have a request like : 

``` js
vm.$http.post('/url', {email: 'my-email+mytag@gmail.com'}, function() { ... });
```

The + char is removed and I do not find why.
Chrome send : `my-email mytag@gmail.com`

**Comment by jmasar** [comment]
I'm commented out these three lines of code  and now I'm able to send the &, =, and + characters.  I'm not sure what this does to replace the values after they've been encoded, so I hesitate to recommend it, but it's working now.


    function encodeUriSegment(value) {

        return encodeUriQuery(value, true);
            //replace(/%26/gi, '&').
            //replace(/%3D/gi, '=').
            //replace(/%2B/gi, '+');
    }
