### ISSUE TITLE
can't send json request 

### ISSUE THREAD

**Issue by longdajiangjun** [pagekit/vue-resource#512]
when I send http get method,
http://localhost/loaduser?paramsJson={%22dbId%22:%221860105%22,%22userId%22:%2250836360105%22}&sign=64f8919307e262bac9f09d6b033ae4e7

it always change to 
http://localhost/loaduser?paramsJson=&sign=64f8919307e262bac9f09d6b033ae4e7

where is paramsJson going?

**Comment by luqingxuan** [comment]
try encodeURIComponent(paramsJson)?
