### ISSUE TITLE
XMLHTTPRequest returns null in response

### ISSUE THREAD

**Issue by sd-knight** [pagekit/vue-resource#513]
device:  HUAWEI P6-U06
android version: 4.2.2
system version: Emotion os 1.6

reason: 
```
xhr.responseType = 'blob';
```

when the resonpse is null, Response.json() catch a error.

**Comment by Gavin-YYC** [comment]
same device
same problem
in other advance devices the response is an Object, but in HUAWEI P6, the response is null.
