### ISSUE TITLE
When vue-resource work in a component's life?

### ISSUE THREAD

**Issue by Su9Tail** [pagekit/vue-resource#514]
When i use `this.$http.get()` in `beforeCreate()` to fetch data from server, and i commit a mutation to store data in `vuex` when response. But when I get data from `this.$store.state`, it was null. So I don't know what's wrong. HELP!!!

**Comment by luqingxuan** [comment]
i think u should try use mounted method, but not beforeCreate, 
maybe there has something with vue lifecycle
