### ISSUE TITLE
把源码中jsonp的回调'_jsonp'改成‘jsonp’

### ISSUE THREAD

**Issue by AceLing** [pagekit/vue-resource#515]
下划线_的_问题

在调用jsonp时，callback参数的值是_jsonp开头的，包含的下划线会被某些接口当作非法字符处理，导致无法正常完成请求。
希望能够把下划线去掉。

谢谢！

**Comment by LancerComet** [comment]
Vue-Resource 没有可以修改此参数的地方，如果不介意，可以试试 [Vue-JSONP](https://github.com/LancerComet/vue-jsonp) :)
