### ISSUE TITLE
CORS cookies don't sent

### ISSUE THREAD

**Issue by jiyifun** [pagekit/vue-resource#520]
CORS cookies dont sended with this options.
```
Vue.http.options.credentials = true
Vue.http.options.xhr = {withCredentials: true}
```

**Comment by cruonline** [comment]
second this.
I have also issues with sending CORS cookies

**Comment by gotraveltoworld** [comment]
I use 'interceptors' to set all pre-requests, current it's work

Example:
~~~
Vue.http.interceptors.push((request, next) => {
    request.credentials = true;
    next();
});
~~~

**Comment by zhangman8667** [comment]
Vue.http.interceptors.push((request, next) => {
    request.credentials = true;
    next();
});

is right
