### ISSUE TITLE
how can handle the router in interceptors

### ISSUE THREAD

**Issue by chao-hua** [pagekit/vue-resource#528]
i use the vue-router and vue-resource,
i want to make a common control to do this :base on request to handle router do some jump.
e.g: request tell me this user have login in other palce, so i need  jump to login page.

**Comment by zhangman8667** [comment]
router.beforeEach((to, from, next) => {
  var userInfo = {}
  if (window.localStorage && window.localStorage.userInfo) {
    userInfo = JSON.parse(window.localStorage.userInfo)
  }
   if (to.path === '/login' || to.path === '/register') {
    next()   // 一些url不需要拦截
  } else if (userInfo.uid) { // 用户没登录跳转登录页面
    next()
  } else {
    next({ path: '/login' })
  }
  // 登录拦截
})
在router.js里面加这个方法做拦截
