### ISSUE TITLE
Using ES6 fat arrow functions in interceptors gives wrong scope.

### ISSUE THREAD

**Issue by dobromir-hristov** [pagekit/vue-resource#532]
Please note in the docs that if you use ES6 `() => {}` style function in the first callback for interceptors, the scope of `this` is NOT the current Vue instance, but rather an empty object.
```js
Vue.http.interceptors.push(function (request, next) {
  next((response) => {
      console.log(this)
  })
})
```
This is how I managed to get it working.

**Comment by steffans** [comment]
Use a normal function, arrow functions inherit the outer scope.
 
```js
Vue.http.interceptors.push(function (request, next) {
  next(function (response) {
      console.log(this)
  })
})
```

**Comment by canol** [comment]
Would be nice to have a solution for arrow function usage for interceptors. I am using ESLint with Airbnb rules and it complains when I use anonymous functions instead of arrow functions (of course I can disable it for that specific line but I would prefer not disabling it).

**Comment by dobromir-hristov** [comment]
Use named functions.
`Function next(){}`

**Comment by canol** [comment]
@dobromir-hristov I checked out current documentation but I can't seem to find information on next() function, can you give example code? And what exactly does next()?
