### ISSUE TITLE
chrome  Provisional headers are shown 

### ISSUE THREAD

**Issue by w550** [pagekit/vue-resource#535]
"vue-resource": "^1.0.3",
 "vue": "^2.1.8",
不停的用chrome 写个死循环去求情数据
 while(true){
this.$http.get('http://localhost:8086/')
}
然后过了一段时间
所有的请求都失败了。
都只返回 Provisional headers are shown 
抓包看了。请求没有出去。
当前的 windows 换个用户登录就正常。

**Comment by yhnbgfd** [comment]
https://segmentfault.com/q/1010000000364871
```
我也遇到这样的问题，是这样解决的：
在按钮点击事件中加上这一句：e.preventDefault(); 
原因可能是点击按钮时触发了表单提交，同时又ajax了。
```
