### ISSUE TITLE
Vue-Resource Post-Request no data

### ISSUE THREAD

**Issue by rajvino227** [pagekit/vue-resource#543]
I try a POST Request with Vue-Resource (with data):
```
this.$http.post('subscribe', {email: this.email, hp: this.address}).then((val) => {
       console.log(val);
});
```
But if i try to print_r($_POST), there is an empty array.
I am using http post insted of $.ajax but the problem was "response" from the always null.

If i do this with jquery:
```
$.ajax({`
        url: 'subscribe',
        type: 'post',
        data: {
          email: 'email',
          name: 'name'
        }
      }).done(function(val) {
        console.log(val);
      })
```
It works fine :/

this.$http.post(....) does not work. Any help would be appreciated?

**Comment by pwaldhauer** [comment]
Maybe it's related to https://github.com/pagekit/vue-resource/issues/531?

**Comment by sanyashvets** [comment]
up
have same error

**Comment by jefflivsky** [comment]
I confirm: this.$http.post(....) does not send params to server

**Comment by rajvino227** [comment]
The vue-resource 1.3 version not support for $http.post but install below version now it's working fine

like vue-resource 0.93 version

**Comment by sanyashvets** [comment]
so, still doesnt works on last version!

**Comment by steffans** [comment]
The request is JSON encoded, see http://stackoverflow.com/questions/19004783/reading-json-post-using-php#answers-header

**Comment by sanyashvets** [comment]
I finally get understood why does it wont work. It just want to send empty object, if no data required with post method :D
ex. `this.$http.post('some/url', {} )
