### ISSUE TITLE
response.data is null when get local json file

### ISSUE THREAD

**Issue by zhoou** [pagekit/vue-resource#545]
here is my code :
<blockquote><code>
<p>let resource = self.$resource('login.json')</p>
<p>resource.get().then((response) => {</p>
    <p>let result = response.data</p>
    <p>console.log(response)</p>
<p>})</p>
</code></blockquote>

Then the response is this :

<blockquote><code>
<p>bodyText:PromiseObj</p>
<p>     context:undefined</p>
<p>     promise:Promise</p>
<p>    __proto__:Promise</p>
<p>         [[PromiseStatus]]:"resolved"</p>
 <p>        [[PromiseValue]]:"[{↵  name: 'admin',↵  password: 'admin123',↵  group: 'admins'↵}]↵"</p>
 <p>        __proto__:Object</p>
<p>data:null</p>
</code></blockquote>

The  [[PromiseValue]] has value , but data is null , i  don't know why , please help...

**Comment by Ceall8650** [comment]
the same problem......

**Comment by steffans** [comment]
@zhoou Does it work for in latest v1.2.1 ?

**Comment by zhoou** [comment]
I have try, but still didn't work

**Comment by Ceall8650** [comment]
I found the json format was wrong in my local json file
After fixed it, I can received data from response
try to check the json format in the file

**Comment by tarpey** [comment]
My JSON is valid and it finds the file but the body is still `null`.

```javascript
this.$http.get('data.json').then( response => {
  console.log(response);
});
```

**Comment by dotneet** [comment]
data property is defined here.
https://github.com/pagekit/vue-resource/blob/develop/src/http/interceptor/body.js

To get a data property your response must pass test either:
 - Content-Type is 'application/json'
 - response text has a valid format as a json.

Check your json whether it can pass following test:

```
function isJson(str) {

    var start = str.match(/^\[|^\{(?!\{)/), end = {'[': /]$/, '{': /}$/};

    return start && end[start[0]].test(str);
}
```

**Comment by kennardconsulting** [comment]
@dotneet 's statement is correct, but his `isJson` function returns true for invalid JSON, which could be misleading. Test your JSON using `JSON.parse( str )` instead
