### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by faxal** [pagekit/vue-resource#547]
^

**Comment by jasonbodily** [comment]
I have to add my curiosity here as well. I have a lot of apps I would love to roll over to Vuejs, but I'm surprised at how undeveloped the options for data modeling are. How is Vuejs so popular and yet doesn't solve basic REST functionality for classes? This project (the only attempt at solving the data layer problem) seems rather abandoned. What's the plan here?

**Comment by jasonbodily** [comment]
Answering our own ponderings: https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4#.plvlsw7w5

Yes, it looks like vue-resource has been dropped.

**Comment by faxal** [comment]
Thanks for the link. That explains a lot of things.
