### ISSUE TITLE
Missing Response headers

### ISSUE THREAD

**Issue by KrisBobLea** [pagekit/vue-resource#549]
There has some data in headers from Response,such as X-Pagination-total,Link e.c.
But I can not get through response.headers.getAll().

And I have set the Access-Control-Expose-Headers in backend.

**Comment by krissss** [comment]
response.headers.getAll() need a name like getAll('X-Pagination-total')

see source code in `/src/http/headers.js`

**Comment by dettmar** [comment]
Same here, `response.headers.getAll()` is always returning `[]` an empty array.

**Comment by krissss** [comment]
you need set Access-Control-Expose-Headers in backend.
like:
`header('Access-Control-Expose-Headers: X-Pagination-Current-Page,X-Pagination-Page-Count,X-Pagination-Per-Page,X-Pagination-Total-Count');`
