### ISSUE TITLE
Query params root

### ISSUE THREAD

**Issue by stephan-v** [pagekit/vue-resource#551]
Is there currently a way to query params for every request?

I can't seem to find it in the documentation and manually adding params to the options object seems to do nothing. 

Cheers.

**Comment by steffans** [comment]
You can create a resource with the params, see https://github.com/pagekit/vue-resource/blob/develop/docs/resource.md#methods

or you can create an interceptor which sets the params, see https://github.com/pagekit/vue-resource/blob/develop/docs/http.md#request-processing
