### ISSUE TITLE
Vue Resource should not be imported within Vuetable.vue

### ISSUE THREAD

**Issue by brandonferens** [pagekit/vue-resource#555]
In my opinion, requiring the use of `vue-resource` should be up to the developer. I am already including `vue-resource` and as such, the error `Cannot redefine property: $url` gets thrown. 

Please remove the import and force developers to pull it in themselves as a dependency.

Unless of course there is a specific reason for this. I would also like to see the ability to change out `vue-resource` for another similar package like axios.

**Comment by brandonferens** [comment]
Sorry, posted this to the wrong project

**Comment by lmj0011** [comment]
see: https://github.com/ratiw/vuetable-2/issues/55
