### ISSUE TITLE
I have a question about configration,why the root doesn't work?

### ISSUE THREAD

**Issue by YanwuSenlu** [pagekit/vue-resource#558]
I have import vue-resource and Vue.use it，I also config as the guide
`http: {
    root: 'http://222.***.***.126:8018',
    headers: {
      Authorization: 'Basic YXBpOnBhc3N3b3Jk',
    },
  },`
but，in my components ,when I use this.$http.get("/myAPI"),
the network is request localhost:8080,but not request the root?
By the way,I use the vue-cli to init my project with the webpack template.

**Comment by steffans** [comment]
The root is only prepended on relative paths, use `this.$http.get("myAPI")`
