### ISSUE TITLE
post请求传参数问题

### ISSUE THREAD

**Issue by zhangman8667** [pagekit/vue-resource#559]
self.$http.post('/main/ss', {}, {params: params}).then((res) => {
    })
post请求三个参数，第一个url，第二个 request.body, 第三个 request.params

怎么传参能像ajax的post请求一样，把参数放在 Form Data里面呢？
现在放在request.body里面是Request Payload
放在request.params里面是 Query String

**Comment by gotraveltoworld** [comment]
Reference document 'FormData' [FORM](https://github.com/pagekit/vue-resource/blob/develop/docs/recipes.md#forms).

You can try this method.

**Comment by zhangman8667** [comment]
body里面的数据类型是 object fromData string三种
转成放fromData类型只能用
var formData = new FormData();

  // append string
  formData.append('foo', 'bar');
这种方式吗？

**Comment by zhangman8667** [comment]
已经解决了
加全局方法
Vue.http.options.emulateJSON = true

**Comment by JasonGaoG** [comment]
Vue.http.options.emulateJSON = true does not work with IE9, anyone knows why? thanks .

**Comment by zaxlct** [comment]
刚好我也遇到这个问题，可能我没仔细看文档，在文档里找了半天没找到
