### ISSUE TITLE
Vue2.0 SSR for Node: got package include arrow function 

### ISSUE THREAD

**Issue by solome** [pagekit/vue-resource#561]
In https://github.com/pagekit/vue-resource/blob/develop/test/webpack.config.js, 

```
 exclude: /node_modules/
```
& https://github.com/pagekit/vue-resource/blob/develop/src/http/client/node.js include

```
const client = require('got');
```

but `got` package include arrow function(ie not support).

**Comment by steffans** [comment]
You need Node.js 4 or higher

**Comment by solome** [comment]
Usually, we need bundle for browser. Node is used normally.

**Comment by steffans** [comment]
Usually the browser bundle should not resolve the `require('got')`, see for example webpack (https://github.com/webpack/webpack/issues/151)

**Comment by solome** [comment]
@steffans thanks.
