### ISSUE TITLE
timeout 设置无效

### ISSUE THREAD

**Issue by junjieit** [pagekit/vue-resource#563]
"vue-resource": "1.2.0"
`Vue.http.post(url,data,{timeout:0}).then(
        (response) => {
         console.log(response)
        },(response) => {
            console.log(response)
        });`

设置了timeout无效，还是会报超时。

**Comment by RalfZhang** [comment]
timeout 设置成 0 应该会瞬间就超时吧……

**Comment by junjieit** [comment]
@RalfZhang 不会的，按理来说 设置成0 应该是不限超时时间。
