### ISSUE TITLE
Post Requests Not Sending Regex Expressions

### ISSUE THREAD

**Issue by maniac0059** [pagekit/vue-resource#564]
When sending a post request with a regex expression in the body, the expression is replaced with an empty object.

For example:

`this.$http.post('/fds', {
                search: /hi/i
            });`

sends the request payload as "{search: {}}". This is also the case when using the regex constructor:

`this.$http.post('/fds', {
                search: new Regexp("hi","i")
            });`

**Comment by steffans** [comment]
You can't send `Regex`objects since they are not JSON serializable.
