### ISSUE TITLE
Get the amount of request in queue

### ISSUE THREAD

**Issue by gabrielbuzziv** [pagekit/vue-resource#565]
How can i use vue resource to know how much requests still pending?

for exemple, when change the page i run 3 request, and i want to do something only when the last one (any of the three request can finish as last), how can i know if the "queue of requests" is done.

**Comment by steffans** [comment]
Each request returns a `Promise`, use `Promise.all(...)` to synchronize them. See https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
