### ISSUE TITLE
EDGE - SCRIPT7002: XMLHttpRequest: Network Error 0x2ef3, Could not complete the operation due to error 00002ef3

### ISSUE THREAD

**Issue by ozee31** [pagekit/vue-resource#568]
Vue@2.2.1
Vue-reource@1.2.0

With EDGE i have the error
`SCRIPT7002: XMLHttpRequest: Network Error 0x2ef3, Could not complete the operation due to error 00002ef3` when I run a query

Do you have any explanation?

**Comment by steffans** [comment]
Which Edge version do you use ? Can you create a example for this on https://jsfiddle.net, for further debugging.

**Comment by ozee31** [comment]
It's not a bug with vue-resource.

Edge fails to connect with my virtual machine with vagrant

Sorry,
