### ISSUE TITLE
php $_GET[];can not accept the data from vue-resource!

### ISSUE THREAD

**Issue by admin00001** [pagekit/vue-resource#574]
js:
var getdata = {a:1111,b:22222};
                console.log(getdata);//is a Object!
                this.$http.get('/php/xxx',getdata).then(response => {
                  
                    console.log('success:');
                    console.log(response.body);
                }, response => {
                    //...
                });
php:
function xxx(){
   if ($_GET){
    $a = $_GET['a'];

    $b = $_GET['b'];
    exit(json_encode(array($a,$b)));//this is null!   how can i accept the data????????????
    }
}

**Comment by ricardobanegas** [comment]
The second argument is an `options`-object. You should send your parameter data like this: 

```this.$http.get('/php/xxx', { params: getdata )(response => {```

From documentation:

`this.$http.get('/someUrl', [options]).then(successCallback, errorCallback);`
