### ISSUE TITLE
SCRIPT5007: 无法获取未定义或 null 引用的属性“isReady” 

### ISSUE THREAD

**Issue by dingwl** [pagekit/vue-resource#578]
ie9下报
![image](https://cloud.githubusercontent.com/assets/23382943/23821174/6e29053c-0665-11e7-987e-43c12e7c071d.png)

**Comment by shangxinbo** [comment]
同求

**Comment by JustinYi922** [comment]
同求：SCRIPT5007:无法获取未定或null 引用的属性“getHostNode”

**Comment by ruth8** [comment]
一样的报错  咋整 我是在ie edge下

**Comment by gaoshijun1993** [comment]
请问楼上的都是怎么解决的?
