### ISSUE TITLE
Can't use global Vue with webpack ProvidePlugin ?

### ISSUE THREAD

**Issue by wenkanglin** [pagekit/vue-resource#582]
### Reproduction Link

https://github.com/wenkanglin/webpack-vendor-order

### Steps to reproduce

````
> npm i // yarn
> npm run dev
````
You will find the console will show error. Remove the annotation of `src->api->index.js->line 7`, the console will not show any error.

### What is Expected?

within `vue 1.x`, use the `vue-resource` by the code:
````
import Vue from 'vue'
import VueResource from 'vue-resource'

Vue.use(VueResource)

Vue.http.get(url).then(...)
````
But I can use the `webpack ProvidePlugin` that makes `Vue.use` automatically:
````
// webpack.config.js
module.exports = {
  ...
  plugins: [
    new webpack.ProvidePlugin({
      Vue: 'vue',
      'window.Vue': 'vue'
    })
  ]
}

// main.js
Vue.http.get(url).then(...) // Don't use Vue.use
````

### What is actually happening?

However, within `vue 2.x`, the `vue-resource` doesn't work with above code and cause error:
````
Uncaught TypeError: Cannot read property 'get' of undefined
````

**Comment by steffans** [comment]
Vue is not globally available on `window` so you have to do `Vue.use(VueResource)` to register it.

**Comment by wenkanglin** [comment]
@steffans But we can use `webpack.ProvidePlugin` to avoid add `Vue.use(VueRouter)` or `Vue.use(Vuex)` manually. Why `Vue.use(VueResource)` can not ?

**Comment by steffans** [comment]
Actually `Vue.use(VueRouter)`and `Vue.use(Vuex)` have to be registered too, see docs: https://router.vuejs.org/en/installation.html

**Comment by wenkanglin** [comment]
Hmmm! I can't see anything that can explains what's you say. And Can you help me to see why it can avoid use `Vue.use(VueResource)` by use [the weird point](https://github.com/wenkanglin/webpack-vendor-order#weird-place)

**Comment by QoVoQ** [comment]
I think `webpack.ProvidePlugin` only provide us the possibility to have access to the variables globally we defined in the file webpack.config.js.
  However, Webpack will not actually load the package(in this case: vue-resource) if you don't have any reference of it  in your code.
  If you reference VueResource in any form or just replace `Vue.use(VueResource)` with `console.dir(VueResource)`, everything also works.
  The reason why you don't have to call `Vue.use(Vuex)` is that you reference vuex by the following code
`export default new VueRouter({` -- router/index.js
