### ISSUE TITLE
浏览器控制台无数据预览，但console可以打印

### ISSUE THREAD

**Issue by htank-wang** [pagekit/vue-resource#587]
我发了个get请求 在chrome控制台看不到preview的数据,response也没有数据，但console可以打印，这个是什么原因？
jquery ajax 每次都可以看到数据预览

**Comment by zhenhappy** [comment]
同样遇到这个问题，但是后来莫名其妙的就好了

**Comment by lyixuan** [comment]
我也遇到同样的问题，chrome控制台看不到preview数据，但是用Firefox可以看到。

**Comment by heymalio** [comment]
#566
