### ISSUE TITLE
response.data is null when response data includes '\t' special character

### ISSUE THREAD

**Issue by 786320861** [pagekit/vue-resource#590]
## here is an example that is from Interface:
`"{"firstYear":2017,"firstMonth":4,"firstDay":10,"firstHour":2,"firstMinute":1,"hourData":[{"x":1491789678000,"y":1,"mediaName":"中国钢铁工业协会网	"}]}"`

there is a '\t' character after "中国钢铁工业协会网", then the response.data is null, and i can't get the actual response data from response.
在中国钢铁工业协会网后面有一个制表符，response.data就为null。
### What is Expected?
when the response data is not a standard json, can you expose an additional key to preserver what the interface response?
当后台接口返回数据不是一个标准的json数据时，能不能增加一个字段用来保存后台返回的数据？

**Comment by steffans** [comment]
The `response.data` gives you the parsed `body`, to get the unparsed body use `response.bodyText` or `response.text()`

**Comment by 786320861** [comment]
thank you!
