### ISSUE TITLE
Where to set global header configuration values?

### ISSUE THREAD

**Issue by nueverest** [pagekit/vue-resource#591]
On this page https://github.com/pagekit/vue-resource/blob/develop/docs/config.md it shows how to set global header values.

```javascript
Vue.http.options.root = '/root';
Vue.http.headers.common['Authorization'] = 'Basic YXBpOnBhc3N3b3Jk';
```

Which file should contain these lines?

I am using vue-cli and vue-router.

Requesting that the documentation explain where to set global Vue.http options.

**Comment by andreapavoni** [comment]
Wherever you require/import Vue itself should be ok

**Comment by gpassero** [comment]
I set the root and Authorization header globally in main.js. The root path worked, but the Authorization header did not.
When executing this.$http.get() the app request the server with HTTP method "OPTIONS", which is denied by the server. Is it possible to not send this method before the GET call?

**Comment by gpassero** [comment]
I solved my problem by adding this to the end of my PHP web service script:

```php
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
	header('Allow: OPTIONS,GET,POST');
	header('Access-Control-Allow-Methods: OPTIONS,GET,POST');
	header('Access-Control-Allow-Headers: authorization');
	exit();
}
```

My Apache server was not configured to accept those kind of requests and I didn't have access to the server configuration.
