### ISSUE TITLE
Why the url path has '//'

### ISSUE THREAD

**Issue by wi-cuckoo** [pagekit/vue-resource#592]
### Reproduction Link
I just config option Vue.http.options.root = 'http://192.168.3.2:5000/'
and use resource as $resource('auth/login')
why the request path changed to http://192.168.3.2:5000//auth/login

**Comment by brianirish** [comment]
Try removing the trailing forward slash at the end of your root value, after the `:5000`.

**Comment by steffans** [comment]
Fixed in v1.3.2
