### ISSUE TITLE
Provisional headers are shown and pending requests

### ISSUE THREAD

**Issue by TarikAmine** [pagekit/vue-resource#594]
Hello, i have a problem with vue-resource causing a **Provisional headers are shown** on chrome,  using Jquery on the other hand work without any problem

**the problem only happens with chrome + vue-resource**

![Error](http://image.prntscr.com/image/fb5cc3b92bf64c69bec6e0762dc861ca.png)

### Reproduction Link
Chrome 57.0.2987
Windows 7

a simple call set with setInterval
https://jsfiddle.net/7vo2s8z3/1/

### Steps to reproduce
usually it happens when i leave the page open for a few hours

### What is Expected?
a 200 code response with content served

### What is actually happening?

i get a request with these headers
> Request URL:http://127.0.0.1:8080/monitor/summary.php
> Referrer Policy:no-referrer-when-downgrade
> Request Headers
>
> **Provisional headers are shown**
> Accept:application/json, text/plain, */*
> Content-Type:application/json;charset=utf-8
> Origin:http://127.0.0.1:8080
> Referer:http://127.0.0.1:8080/monitor/
> User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
> X-Requested-With:XMLHttpRequest

and looking at **chrome://net-internals/#events** the cause of failure is 

> 85487: URL_REQUEST
> http://127.0.0.1:8080/monitor/summary.php
> Start Time: 2017-04-18 09:38:43.826
> 
> t=29028 [st=    0] +REQUEST_ALIVE  [dt=24184]
>                     --> priority = "MEDIUM"
>                     --> url = "http://127.0.0.1:8080/monitor/summary.php"
> t=29029 [st=    1]   +DELEGATE_INFO  [dt=24183]
>                       --> delegate_blocked_by = "RedirectToFileResourceHandler"
> t=53211 [st=24183]      CANCELLED
>                         --> net_error = -2 (ERR_FAILED)
> t=53212 [st=24184] -REQUEST_ALIVE

**Comment by black-lotus** [comment]
i have same issue

OS : macOS Sierra
OS Ver : 10.12.4
Browser : Google Chrome
Browser Ver :  58.0.3029.110 (64-bit)

**Comment by javiercbk** [comment]
It's happening to me whenever I use `Vue.http.post` and the request fails. The following request will remain stalled.

**Comment by javiercbk** [comment]
Updating from 1.2.1 to 1.3.4 solved my issue

**Comment by zhanghaiyang1** [comment]
what to upgrade?

**Comment by zhanghaiyang1** [comment]
vue?

**Comment by mattdolge** [comment]
If you want to get rid of the provisional header error you can disable cache and reload the page. Or try busting the cache with a parameter.

**Comment by GzhiYi** [comment]
@mattdolge It doesn't work.😔

**Comment by arun0415** [comment]
In Windows try to looking into your host file(C:\Windows\System32\drivers\etc) entry in my case that did the trick. Hope that helps :)

**Comment by Yogeshsinghbisht** [comment]
How to solve my website problem for [www.openacessjournal.com](https://www.openacessjournal.com/)
