### ISSUE TITLE
跨域全局设置请求添加cookie以后，怎么设置headers？

### ISSUE THREAD

**Issue by yuweilan** [pagekit/vue-resource#601]
请问做过全局跨域，
vue.http.interceptors.push(function(request, next) {
    request.credentials = true;
    next();
});
设置之后，无法设置headers，怎么解决？此时，我在设置emulateJSON时，无效，求解，谢谢

**Comment by eachmawzw** [comment]
Add your headers param name in 'Access-Control-Allow-Headers' at your server code.
For example,
request.headers.set('Authorization', authorization)  // in your vue-resource interceptors

response.setHeader("Access-Control-Allow-Headers", "Authorization") // in your server code
