### ISSUE TITLE
Interceptor to catch a request and re-send it depending on response from server?

### ISSUE THREAD

**Issue by Gacnt** [pagekit/vue-resource#605]
Is there a way to resend a request if the response returns a 401?

I'm trying to use a refreshToken / accessToken system like OAuth 2.0

I'm trying to use an interceptor to catch the response on every request, so that if I get a 401, I can do a post to refresh the accessToken, and then reissue the request, is there a good way to do this utilizing vue-resource or do I need to resort to something like jQuery

```
Vue.http.interceptors.push((request, next) => {
  request.headers.set('x-access-token', localStorage.getItem('token'));

  next(function(response) {
    if (response.status === 401) {
      // Do post request to refresh token

      // Resend {request} and wait for response
    }
  });
});
```

Some fake code for example

**Comment by larscom** [comment]
This is exactly what im looking for also, i think its not possible at the moment ? Basically after you re-send the request and received a response you want to send the last response back to the client.

**Comment by javoski** [comment]
This may help you:
```javascript
Vue.http.interceptors.push((req, next) => {
  req.headers.set('x-access-token', localStorage.getItem('token'))
  next(res => {
    if (response.status === 401) {
    	return new Promise(resolve => {
      	refreshToken().then(_ => {
        	resolve(Vue.http(req))
        })
      })
    }
  })
})
```

**Comment by pgupt** [comment]
> ```js
> next(res => {
>     if (res.status === 401) {
>       return Promise.resolve(refreshToken().then(_ => Vue.http(req)))
>     }
>   })
> ```

I am new to Vue development. Can you help me with the code when I don't have refreshToken method available.

**Comment by gedkirkham** [comment]
@pgupt Create one:

function refreshToken () {
  return Vue
    .http
    .post(process.env.API + '/token/refresh/', {
      refresh: localStorage.getItem('refresh') || null,
    })
    .then(RESP => {
      const TOKENS = RESP.body
      localStorage.setItem('access', TOKENS.access)
      localStorage.setItem('refresh', TOKENS.refresh)
    })
}
