### ISSUE TITLE
this.previousRequest is always undefined

### ISSUE THREAD

**Issue by syn-zeta** [pagekit/vue-resource#606]
### Reproduction Link
https://jsfiddle.net/5o478690/4/

### Steps to reproduce
Browser: Chrome Version 58.0.3029.96 (64-bit)
OS: Mac OS X 10.11.6 (15G31)
Vue-resource: 1.3.1

![resource](https://cloud.githubusercontent.com/assets/26761352/25836885/545b706a-343f-11e7-8809-a8d5c9cc15ff.gif)

### What is Expected?
To have `this.previousRequest` hold a reference to the last pending request which will allow it to be cancelled as documented [here](https://github.com/pagekit/vue-resource/blob/develop/docs/recipes.md#abort-a-request).

### What is actually happening?
`this.previousRequest` is undefined even when there are pending requests.

**Comment by steffans** [comment]
You have to set the `this.previousRequest` property as described in the [recipe](https://github.com/pagekit/vue-resource/blob/develop/docs/recipes.md#abort-a-request).

**Comment by syn-zeta** [comment]
Of course. My bad.

I tried it but calling `abort` on the previous request errors out: https://jsfiddle.net/5o478690/5/

**Comment by syn-zeta** [comment]
@steffans Should I close this issue and create a new one for the error when aborting a previous request?
