### ISSUE TITLE
Support for 'OPTIONS' method?

### ISSUE THREAD

**Issue by italomandara** [pagekit/vue-resource#608]
### Steps to reproduce

There's no mention in the docs so I assume it's not supported

### What is Expected?
I was expecting a shorthand for the the OPTIONS method

### What is actually happening?
$http.options is used for other purposes

can we get a shorthand $http.options (or any name) to support method 'OPTIONS' please? 
I know is rarely used but it's handy when you want to use a form builder

**Comment by steffans** [comment]
Right, options is used for other purposes, change this would cause a breaking change. However you can create a request with passing 'options' as method:

```
$http({url: 'someurl', method: 'options'})
```

**Comment by italomandara** [comment]
I tried and for some reason it doesn't work
