### ISSUE TITLE
Please expose core functionality outside of "Vue only"/component context

### ISSUE THREAD

**Issue by kristianmandrup** [pagekit/vue-resource#612]
Please see https://github.com/bangbang93/vue-fetch/issues/3

Ideally you don't want your service access logic inside your components. Really bad practice, only for hacky/dev/quick test cases... not for real life.

I had to patch up [vue-fetch](https://github.com/bangbang93/vue-fetch) for the same reason as shown [here](https://github.com/kristianmandrup/vue-fetch#outside-component)

**Comment by kristianmandrup** [comment]
I tried to make the [following changes](https://github.com/kristianmandrup/vue-resource/commit/906f6c6b0d419d7ad55e3135a4ee6c0b31d89cf1) to expose the API outside of a "pure Vue component" context. 

Please help out ;) thanks!

**Comment by kristianmandrup** [comment]
Wouldn't want to end up here... The ONE class (aka component) to rule them all!!!

https://vimeo.com/9981123

**Comment by steffans** [comment]
All services are currently exposed `Url, Http, Resource`, this will work:

```js
import { Http } from 'vue-resource'

Http.get('/someUrl').then(response => {   
    // callback ...
});
```
