### ISSUE TITLE
How can i solve No 'Access-Control-Allow-Origin' header is present on the requested resource problem ? 

### ISSUE THREAD

**Issue by mrokt** [pagekit/vue-resource#617]
How can i solve No 'Access-Control-Allow-Origin' header is present on the requested resource problem ?  Can you help me for this issue ?

**Comment by flowck** [comment]
Hi @mrokt, 

What platform / language are you using in back-end? You need to enable in your back-end app external access in your back-end.

If you're using Nodejs / Express just create a Middleware like this:

```
app.use("/your/api/path", (req, res, next){
       res.header("Access-Control-Allow-Origin", "*");
});
```

**Comment by mrokt** [comment]
i'm not using backend. Making a API call with Vue.js. Getting cors error.

**Comment by jofftiquez** [comment]
I believe you should adjust the backend to allow the requesting origin to the `cors`. If you are using `nodejs` you can use `npm install cors`.

**Comment by raadsaeed445** [comment]
![Uploading 14506-e2b41df0a680e582ce5385.jpg…]()

**Comment by raadsaeed445** [comment]
![14506-2d57ce23b39c929fe7334f](https://user-images.githubusercontent.com/36119288/151660816-61922ea9-6d03-45cc-ab47-99f8c26e7668.jpg)
