### ISSUE TITLE
Chrome creates Blob for body, others browsers don't

### ISSUE THREAD

**Issue by nelfer** [pagekit/vue-resource#623]
### Reproduction Link
I do not have a publicly available JSON end point that returns empty
** This might be a Chrome bug, but I'm not sure **
Using vue-resource 1.1.1

### Steps to reproduce
Using get() for an AJAX request, it returns empty (nothing in the body). Other browsers, like Firefox and Internet Explorer return a response with body set to null. Content type in request and response is set to `application/json`. Chrome, however, returns a Blob object:
![image](https://user-images.githubusercontent.com/22993432/26982732-5392d76e-4d07-11e7-8e2e-85183afa2c10.png)
 And so here is where I'm not sure if it's vue-resource that needs to check the response when trying to parse it or if it's Chrome that is doing something funky. Because if I use the method response.json() the promise fails in Chrome saying there's something invalid parsing the JSON and it doesn't fail in other browsers.
Looking at the network response, the body is indeed empty (not even `{}`).

### What is Expected?
In all supported browsers, for response.body to be null if content type is `application/json` and the body content is empty.

### What is actually happening?
Only in Chrome, response.body is being created as a Blob object.

**Comment by steffans** [comment]
Can you upgrade vue-resource to 1.3.4 and check if this error still happens.
