### ISSUE TITLE
Calling abort() on a previous request errors out.

### ISSUE THREAD

**Issue by syn-zeta** [pagekit/vue-resource#625]
Previous issue reference: https://github.com/pagekit/vue-resource/issues/606

### Reproduction Link
https://jsfiddle.net/5o478690/6/

### Steps to reproduce
Browser: Chrome Version 58.0.3029.110 (64-bit)
OS: Mac OS X 10.11.6 (15G31)
Vue-resource: 1.3.4

1. Open the above linked fiddle
2. Open JavaScript console
3. Type a few characters quickly in the search bar

### What is Expected?
Pending requests to get aborted.

### What is actually happening?
![image](https://user-images.githubusercontent.com/26761352/27165612-fefd7f46-5149-11e7-9a73-de06db9a0122.png)

![image](https://user-images.githubusercontent.com/26761352/27165684-79722786-514a-11e7-937b-fda30bda263e.png)

**Comment by steffans** [comment]
You need to provide an error callback, see https://jsfiddle.net/5o478690/7/

**Comment by syn-zeta** [comment]
Thank you, Steffan.

Interestingly, though, the pending requests are actually not aborted:

![abort](https://user-images.githubusercontent.com/26761352/27172238-5e5cf2c2-5169-11e7-9eec-e1fb42462fb6.gif)

I'll try to dig more as I get a chance, unless you already know if I missed something else.

**Comment by steffans** [comment]
This is happens only for jsonp, because there is no way to arbor it. If you use xhr the request will be actually aborted.

**Comment by syn-zeta** [comment]
Makes sense. Thank you.
