### ISSUE TITLE
Cannot set header "date"

### ISSUE THREAD

**Issue by Adavo** [pagekit/vue-resource#629]
### Reproduction Link
https://jsfiddle.net/pjjr7e7m/1/

### Steps to reproduce
On Chrome 59, Windows 10.
Run the jsfiddle and open your chrome dev tool in order to check the ip request headers.

### What is Expected?
The date header should be defined to the appropriate value

### What is actually happening?
The date header is not set.
As you can see the Authorization is.

**Comment by steffans** [comment]
See: https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name
