### ISSUE TITLE
why in some browser, i can't get the get Method's params?

### ISSUE THREAD

**Issue by evilemon** [pagekit/vue-resource#633]
i can read the params in chrome firefox ,but in Baidu browser & some lower version chrome, it does't work.

"vue-resource": "^0.7.0",

**Comment by evilemon** [comment]
中文：有的浏览器能在url里放参数，而有的就不行。百度浏览器和一些低版本的win7 chrome  get请求无法传参数，都是空

**Comment by evilemon** [comment]
求解答~！

**Comment by lc-soft** [comment]
所以，你就是不肯贴出示例代码？
