### ISSUE TITLE
response object lost Content-Disposition header

### ISSUE THREAD

**Issue by toby3d** [pagekit/vue-resource#638]
Headers logs from my simple go-router:
```
Vary:[Origin]
Access-Control-Allow-Origin:[*]
Last-Modified:[Mon, 07 Aug 2017 18:49:53 GMT]
Content-Type:[image/png]
Accept-Ranges:[bytes]
Content-Length:[8891]
Content-Disposition:[attachment; filename=100percent.png]
```

But:
![image](https://user-images.githubusercontent.com/5412322/29043718-c4515a14-7bd5-11e7-906a-23643408b460.png)

**Comment by toby3d** [comment]
Oh, shit, fucking CORS...

**Comment by sane5ek** [comment]
To fix this, add 'Allow-Access-Expose-Headers' on server. Example (Django):
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(path_to_file)
    response['Access-Control-Expose-Headers'] = 'Content-Disposition'

**Comment by rumbarum** [comment]
@sane5ek  You save me! No one tells `response['Access-Control-Expose-Headers'] = 'Content-Disposition'`.
