### ISSUE TITLE
post() makes a GET request

### ISSUE THREAD

**Issue by truefusion** [pagekit/vue-resource#646]
Using vue-resource v1.3.4.

### Steps to reproduce
Minimal steps to reproduce.
```
this.$http.post('/test', {});
```
The problem seems to be caused by a URL that does not end with a forward slash.
Works fine if I add the forward slash at the end.
```
this.$http.post('/test/', {});
```

### What is Expected?
If I use post(), it should be a POST request.

### What is actually happening?
Gets converted into GET silently.

**Comment by a2sc** [comment]
Same issue here. Should is use axios instead ?

**Comment by steffans** [comment]
I cannot reproduce this issue, here is a jsfiddle: https://jsfiddle.net/sx45zrte/

**Comment by truefusion** [comment]
I have updated the fiddle that reproduces the problem: https://jsfiddle.net/sx45zrte/1/

**Comment by steffans** [comment]
![bildschirmfoto 2017-08-29 um 16 16 58](https://user-images.githubusercontent.com/321013/29825781-b471138a-8cd5-11e7-8e07-ecb7f4452582.png)

The POST request to `/echo/json` gets redirected to `/echo/json/` by the jsfiddle server, thats why it will become a GET. Somehow the Chrome Devtools don't show the redirect, try Firefox instead.
