### ISSUE TITLE
params object should be used as params in the url and not query.

### ISSUE THREAD

**Issue by jofftiquez** [pagekit/vue-resource#650]
I was having and error on my express server, saying that `req.params.foo` is undefined. 

On my vue app I did the request as: 

```
this.$http.get('sumFuk', {params: { foo: 'some value' }});
``` 
Normally, naming the object `params`, I would expect that I would get the `foo` from `req.params`. But upon investigating, url was formatted as `https://some.api.com/sumFuk?foo=some value` which doesn't make sense because this is a `query` and is accessible thru `req.query.foo`. 

I could be wrong though, but doesn't it make more sense to name the object as `{query:Object}`

**Comment by steffans** [comment]
Yes, the `params` option sets the query parameters or parameters in the uri, see https://medialize.github.io/URI.js/uri-template.html
