### ISSUE TITLE
error in $http.post

### ISSUE THREAD

**Issue by elviskudo** [pagekit/vue-resource#655]
Hi,

i just find issue
No 'Access-Control-Allow-Origin' header is present on the requested resource.
my code no headers in `this.$http.post`

but i added headers like this
```
{
  headers: {
    // 'Access-Control-Allow-Origin': true,
    emulateJSON: true,
    emulateHTTP: true
  }
}
```
i got error like this `(in promise) TypeError: str.replace is not a function`
how can i fixed this?
thanks

**Comment by dhazelett** [comment]
You need to add that header as a response from your api server.

`Access-Control-Allow-Origin: http://my.vue.app:8080`

**Comment by elviskudo** [comment]
thanks for your respond, i already added your solution, but still the same error `str.replace is not function`

**Comment by dhazelett** [comment]
Can you post a snippet of the offending code?

**Comment by elviskudo** [comment]
in my vue app (separate app with laravel backend)

`
var payload = {
            name: this.name,
            start: this.start,
            expired: this.expired,
            supplier_name: this.supplier_name,
            type: this.type,
            adult: this.adult,
            adult_change: this.adult_change,
            adult_amount: this.adult_amount,
            children: this.children,
            children_change: this.children_change,
            children_amount: this.children_amount,
            infant: this.infant,
            infant_change: this.infant_change,
            infant_amount: this.infant_amount
          }
          this.$http.post(apiUrl + 'discount', {
            payload: payload
          }, {
            headers: {
              // 'Access-Control-Allow-Origin': true
              emulateJSON: true,
              emulateHTTP: true
            }
          })
            .then(response => {
              console.log(response)
            })
`
in my laravel backend CORS:
`
<?php

return [
     /*
     |--------------------------------------------------------------------------
     | Laravel CORS
     |--------------------------------------------------------------------------
     |
     | allowedOrigins, allowedHeaders and allowedMethods can be set to array('*')
     | to accept any value.
     |
     */
    'supportsCredentials' => true,
    'allowedOrigins' => ['http://localhost:8080'],
    // 'allowedOrigins' => ['*'],
    'allowedHeaders' => ['*'],
    // 'allowedHeaders' => ['Content-Type', 'X-Requested-With', 'Origin', 'Accept'],
    'allowedMethods' => ['*'], // ex: ['GET', 'POST', 'PUT',  'DELETE']
    'exposedHeaders' => [],
    'maxAge' => 0,
];
`
if i `this.$http.get` data fom laravel backend, data shown
but if `this.$http.post` error
but in postman, no problem with post method
thanks

**Comment by Meekohi** [comment]
@elviskudo `emulateJSON` is an option you can pass to vueresource, not part of the headers:

```
{
  headers: {
    // 'Access-Control-Allow-Origin': true 
  },
  emulateJSON: true,
  emulateHTTP: true
}
```

**Comment by thEpisode** [comment]
And solution for CORS? Same error...

**Comment by aaronpeterson** [comment]
Take a close look at your header values.  They need to be strings.

```javascript
// These are cors request headers which seem superfluous to me but alas:
//Access-Control-Request-Method: POST
//Access-Control-Request-Headers: X-PINGOTHER, Content-Type

// in a vue module...
this.$http.get('reports', {
  params: {some:'value'}, 
  headers: {
    /** 
     * these are optional and tell the server what you'd like permission to do (POST) 
     * and which headers you want access to in the response 
     */
    "Access-Control-Request-Method": "POST",
    "Access-Control-Request-Headers": "X-PINGOTHER, Content-Type"
  }
}
```

Much more important is your server response to both the OPTIONS (in this example the request is OPTIONS /reports) -- 
```
Access-Control-Allow-Origin: http://foo.example
Access-Control-Allow-Methods: POST, GET
Access-Control-Allow-Headers: X-PINGOTHER, Content-Type
Access-Control-Max-Age: 86400
```

Make sure your back-end is sending the right stuff.  [A very well-crafted guide to cors.](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#The_HTTP_request_headers)

**Comment by elviskudo** [comment]
thanks @Meekohi 
my project solved
