### ISSUE TITLE
vue-resource not compliant with IE 10 in Windows Phone 8

### ISSUE THREAD

**Issue by enzodev** [pagekit/vue-resource#657]
This sample code works with my desktop browsers, not with Windows Phone 8 (I don't see: `Test passed` but `Test {{message}}`). As you can see I don't use the method, so it's some parser error ... 

My phone: Nokia Lumia 625 Black - Windows Phone 8.0.10517.150

`

<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Vue Resource tests</title>
	<script src="https://unpkg.com/vue"></script>
	<script src="https://cdn.jsdelivr.net/npm/vue-resource@1.3.4"></script>
    </head>
    <body>	
		
		<div id="app">			
			<div>
				Test: {{message}}
			</div>			
		</div>
		
		<script type="text/javascript">		
			Vue.http.options.emulateJSON = true;
		
			var app = new Vue({
				el: '#app',	
				data: {
					message: 'passed'
				},
				methods: {
					testmethod: function () {
						{
							this.$http.get('/someUrl').then(response => {
								this.message = response.body;
							}, response => {
								this.message = 'failed';
							});
						}
					}
				},				
			})
		</script>			
    </body>
</html>`

**Comment by steffans** [comment]
It doesn't seem like a `vue-resource` issue, if see `Test: {{message}}` it means that vue is even not working.
