### ISSUE TITLE
Can't get progress percent

### ISSUE THREAD

**Issue by willybrauner** [pagekit/vue-resource#674]
I try to get progress percent load in real time, like this : 

```javascript
    let progress = (e) => {
        console.log(e); // return undefined
    }
    Vue.resource(url).get({progress: progress}).then((response) => { ... });
```

this return me multiple "undefied".
Any suggestions ?

**Comment by steffans** [comment]
I added dedicated `uploadProgress` and `downloadProgress` options with v1.5.0. Try the following example, also make sure to enable bandwidth throttling in your browser to simulate slow connections.

```javascript
    let progress = (e) => {
        console.log(e); // return undefined
    }
    Vue.http.get('/someUrl', {downloadProgress: progress}).then((response) => { ... });
```

**Comment by willybrauner** [comment]
I tried your code this but Sadly, it return nothing in my console even if I enable bandwidth throttling in my browser. Another suggestion ? Thanks !
