### ISSUE TITLE
JSONP request catches error despite callback firing

### ISSUE THREAD

**Issue by beningreenjam** [pagekit/vue-resource#679]
### Reproduction Link
https://jsfiddle.net/LqntgLaz/10/

### Steps to reproduce
Request to Flickr public API via JSONP on created lifecycle event, using the required function expression attached to the `window` object with the name of `jsonFlickrFeed`.

Tested on:
Firefox 57.0.4 64-bit (MacOS High Sierra 10.13.3)
Version 64.0.3282.186 (Official Build) (64-bit) (MacOS High Sierra 10.13.3)
Version 11.0.3 (13604.5.6) (MacOS High Sierra 10.13.3)

### What is Expected?
Callback fires without errors and success method within promise fires also

### What is actually happening?
Callback fires ok. Promise catches error with an empty Response object (example below).

```
{
  "url": "https://api.flickr.com/services/feeds/photos_public.gne?tagMode=all&format=json&callback=jsonFlickrFeed&jsonFlickrFeed=_jsonp585991qv8b",
  "ok": false,
  "status": 0,
  "statusText": "",
  "headers": {
    "map": {}
  },
  "body": null
}
```

**Comment by steffans** [comment]
Use the `jsonpCallback` option to the the callback name, see https://jsfiddle.net/LqntgLaz/16/
