### ISSUE TITLE
vue-ressource vs fetch/axios/others

### ISSUE THREAD

**Issue by Shuunen** [pagekit/vue-resource#684]
### Steps to reproduce

I just discovered this repo and the first wondering I had was "when use vue-ressource rather than fetch or axios or another lib ?" 

### What is Expected?

I think the README should explains that briefly and maybe have a small comparison table.

**Comment by diego-lipinski-de-castro** [comment]
this is forgotten,they recommend axios

**Comment by Shuunen** [comment]
What's forgotten ? Who recommend axios ?

**Comment by diego-lipinski-de-castro** [comment]
Here, https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4

**Comment by diego-lipinski-de-castro** [comment]
Agree w/ you. Idk if they are actually updating this, but you could try a pr, by the way, this should be closed now

**Comment by gotexis** [comment]
I was totally confused about the project as well at first glance.

I thought it was something that makes Vue a backend server ;)
